/** Auto-mapped original Township icons. Only confident matches. */
export const GAME_ICON_MAP = {
  "stats": {
    "tca": "/game-icons/T-cash.png",
    "coi": "/game-icons/Coins.png",
    "lvl": "/game-icons/Level.png",
    "win": "/game-icons/First_attempt_win.png",
    "liv": "/game-icons/Lives_send.png",
    "reg": "/game-icons/Regatta.png",
    "hlp": "/game-icons/help.png",
    "exp": "/game-icons/Energy.png",
    "m3l": "/game-icons/M3_Level.png",
    "match3Life": "/game-icons/Lives_x3.png",
    "residents": "/game-icons/Residents.png",
    "wheatCounter": "/game-icons/Wheat.png",
    "defaultOrdersCount": "/game-icons/Game_Token.png"
  },
  "itemsByLabel": {
    "Brick": "/game-icons/Bricks.png",
    "Glass": "/game-icons/Glass.png",
    "Slab": "/game-icons/Slab.png",
    "Pickaxe": "/game-icons/Pickaxe.png",
    "Axe": "/game-icons/Axe.png",
    "TNT": "/game-icons/TNT.png",
    "Jackhammer": "/game-icons/Jackhammer.png",
    "Power Saw": "/game-icons/Electric_Saw.png",
    "Drill": "/game-icons/Drill.png",
    "Rainbow Ball": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png",
    "Bomb + Rocket": "/game-icons/Match-3_Activate_the_Rocket_Power-up.png",
    "Bomb": "/game-icons/Color_Splash_Bomb.png",
    "Mallet": "/game-icons/Hammer.png",
    "Barn Capacity Coupon": "/game-icons/Spacious_Barn_Booster.png",
    "Expansion Coupon": "/game-icons/Expansion_Coupon.png",
    "Load Train/Airport Coupon": "/game-icons/Load_Coupon.png",
    "Train Upgrade Coupon": "/game-icons/Load_Coupon.png",
    "Badge 1": "/game-icons/Badge_1.png",
    "Badge 10": "/game-icons/Badge_10.png",
    "Badge 11": "/game-icons/Badge_11.png",
    "Badge 12": "/game-icons/Badge_12.png",
    "Badge 13": "/game-icons/Badge_13.png",
    "Badge 14": "/game-icons/Badge_14.png",
    "Badge 15": "/game-icons/Badge_15.png",
    "Badge 16": "/game-icons/Badge_16.png",
    "Badge 2": "/game-icons/Badge_2.png",
    "Badge 3": "/game-icons/Badge_3.png",
    "Badge 4": "/game-icons/Badge_4.png",
    "Badge 5": "/game-icons/Badge_5.png",
    "Badge 6": "/game-icons/Badge_6.png",
    "Badge 7": "/game-icons/Badge_7.png",
    "Badge 8": "/game-icons/Badge_8.png",
    "Badge 9": "/game-icons/Badge_9.png",
    "Frame 1": "/game-icons/Frame_1.png",
    "Frame 10": "/game-icons/Frame_10.png",
    "Frame 11": "/game-icons/Frame_11.png",
    "Frame 12": "/game-icons/Frame_12.png",
    "Frame 13": "/game-icons/Frame_13.png",
    "Frame 14": "/game-icons/Frame_14.png",
    "Frame 15": "/game-icons/Frame_15.png",
    "Frame 2": "/game-icons/Frame_2.png",
    "Frame 3": "/game-icons/Frame_3.png",
    "Frame 4": "/game-icons/Frame_4.png",
    "Frame 5": "/game-icons/Frame_5.png",
    "Frame 6": "/game-icons/Frame_6.png",
    "Frame 7": "/game-icons/Frame_7.png",
    "Frame 8": "/game-icons/Frame_8.png",
    "Frame 9": "/game-icons/Frame_9.png",
    "Title 1": "/game-icons/Title_1.png",
    "Title 10": "/game-icons/Title_10.png",
    "Title 11": "/game-icons/Title_11.png",
    "Title 12": "/game-icons/Title_12.png",
    "Title 13": "/game-icons/Title_13.png",
    "Title 14": "/game-icons/Title_14.png",
    "Title 15": "/game-icons/Title_15.png",
    "Title 16": "/game-icons/Title_16.png",
    "Title 17": "/game-icons/Title_17.png",
    "Title 18": "/game-icons/Title_18.png",
    "Title 19": "/game-icons/Title_19.png",
    "Title 2": "/game-icons/Title_2.png",
    "Title 20": "/game-icons/Title_20.png",
    "Title 3": "/game-icons/Title_3.png",
    "Title 4": "/game-icons/Title_4.png",
    "Title 5": "/game-icons/Title_5.png",
    "Title 6": "/game-icons/Title_6.png",
    "Title 7": "/game-icons/Title_7.png",
    "Title 8": "/game-icons/Title_8.png",
    "Title 9": "/game-icons/Title_9.png",
    "Festival": "/game-icons/Style_Festival_Banner.png",
    "Cooking": "/game-icons/Style_Cooking.png",
    "Easter": "/game-icons/Style_Easter.png",
    "Neon": "/game-icons/Style_Neon.png",
    "Underwater Violet": "/game-icons/Style_Underwater_Violet.png",
    "Style 6": "/game-icons/Style_Gold.png",
    "Bubble": "/game-icons/Soap_Bubbles.png"
  },
  "barn": {
    "wheat": "/game-icons/Wheat.png",
    "corn": "/game-icons/Corn.png",
    "carrot": "/game-icons/Carrot.png",
    "sugarcane": "/game-icons/Sugarcane.png",
    "milk": "/game-icons/Milk.png",
    "egg": "/game-icons/Egg.png",
    "cotton": "/game-icons/Cotton.png",
    "paint": "/game-icons/Paint.png",
    "honey": "/game-icons/Honeycombs.png",
    "wool": "/game-icons/Wool.png",
    "bread": "/game-icons/Bread.PNG",
    "cookie": "/game-icons/Easter_Cookie.png",
    "clover": "/game-icons/Clover.png",
    "fabric": "/game-icons/Silk.png"
  },
  "skinsByGroupLabel": {
    "TrainStation": {
      "Default": "/game-icons/Train_Station_Skin.png",
      "Express": "/game-icons/Express_Portal.png",
      "Ghost": "/game-icons/Ghost_Station.png",
      "Disco": "/game-icons/Disco_Station.png",
      "Cowboy": "/game-icons/Cowboy_Station.png",
      "Christmas": "/game-icons/Christmas_Station_Skin.png",
      "Easter": "/game-icons/Easter_Station_Skin.png",
      "Ancient": "/game-icons/Ancient_Settlement.png",
      "Theater": "/game-icons/Theater_Premiere_Event_Theater_Set_Station.png",
      "Chinese": "/game-icons/Lantern_Festival_Event_2023_Chinese_Station_Skin.png",
      "Space": "/game-icons/Martian_Odyssey_Event_2023_Space_Station_Skin.png",
      "Camp": "/game-icons/Forest_Adventure_Event_Training_Camp_Skin.png",
      "Record": "/game-icons/Rock_n_Roll_Festival_Event_Record_Station_Skin.png",
      "Castle": "/game-icons/Brotherhood_of_the_Knights_Event_Castle_Station_Skin.png",
      "Roman": "/game-icons/Italian_Holiday_Event_Roman_Station_Skin.png",
      "Halloween": "/game-icons/Haunted_Halloween_Event_Halloween_Station_Skin.png",
      "Magical": "/game-icons/Magical_Christmas_Event_Christmas_Station_Skin.png",
      "Festival": "/game-icons/Flower_Pass_Event_Flower_Station_Skin.png",
      "Hellas": "/game-icons/Mythic_Pass_Event_Mythic_Station_Skin.png",
      "Gatsby": "/game-icons/Gatsby_Pass_Event_Gatsby_Train_Station_Skin.png"
    },
    "Train": {
      "Christmas": "/game-icons/Christmas_Train_Skin.png",
      "Christmas 2024": "/game-icons/Magical_Christmas_Event_Christmas_Train_Skin.png",
      "Knight": "/game-icons/Brotherhood_of_the_Knights_Event_Knight_Train_Skin.png",
      "Western": "/game-icons/Cowboy_Train.png",
      "Gatsby": "/game-icons/Gatsby_Pass_Event_Gatsby_Train_Skin.png",
      "Halloween 2024": "/game-icons/Haunted_Halloween_Event_Halloween_Train_Skin.png",
      "Easter": "/game-icons/Easter_Express_Train_Skin.png",
      "Rock & Roll": "/game-icons/Disco_Train.png",
      "Festival": "/game-icons/Flower_Pass_Event_Flower_Train_Skin.png",
      "Prehistoric": "/game-icons/Primeval_Express.png",
      "Theatrical": "/game-icons/Theater_Premiere_Event_Theater_Express.png",
      "Mars": "/game-icons/Martian_Odyssey_Event_2023_Mars_Rover_Skin.png",
      "Italy 2024": "/game-icons/Italian_Holiday_Event_Express_Tram_Skin.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2023_Dragon_Train_Skin.png",
      "Ghost": "/game-icons/Ghost_Train.png",
      "Special SP2": "/game-icons/Farm_Express.png",
      "Special SP5": "/game-icons/Thunderbird.png",
      "Special SP8": "/game-icons/Red_Lightning.png",
      "Future 76": "/game-icons/Future_Express.png"
    },
    "Airplane": {
      "Special SP3": "/game-icons/Plane.png",
      "Space": "/game-icons/Ultra_Plane.png",
      "Rock": "/game-icons/Rock_Plane.png",
      "Movie": "/game-icons/A-lister_Jet.png",
      "Halloween 2021": "/game-icons/Ghost_Plane.png",
      "Christmas 2022": "/game-icons/Magical_Christmas_Event_2022_Plane_Skin.png",
      "Easter 2023": "/game-icons/Easter_Fun_2023_Event_Bird_Plane_Skin.png",
      "Sweet": "/game-icons/Sweet_Birthday_Event_Eclair_Plane_Skin.png",
      "Ireland": "/game-icons/Irish_Journey_Event_Lucky_Jet_Skin.png",
      "Fashion": "/game-icons/Fashion_Pass_Event_Fashion_Plane_Skin.png",
      "Classic Music": "/game-icons/Music_Festival_Event_Symphony_Plane_Skin.png",
      "Arab": "/game-icons/Arabian_Pass_Event_Arabian_Plane_Skin.png",
      "Spy": "/game-icons/Spy_Games_Event_Stealth_Aircraft_Skin.png",
      "All Inclusive": "/game-icons/Beach_Vacation_Event_2024_Seaplane_Skin.png",
      "Winter Sport": "/game-icons/Sporty_Winter_Event_Areo_Sleigh_Skin.png"
    },
    "Airport": {
      "Special SP3": "/game-icons/Airport_Skin.png",
      "Space": "/game-icons/Spaceport_Skin.png",
      "Rock": "/game-icons/Rock_Airport.png",
      "Movie": "/game-icons/Cinema_Airport.png",
      "Halloween 2021": "/game-icons/Ghost_Airport.png",
      "Christmas 2022": "/game-icons/Airport_Skin.png",
      "Easter 2023": "/game-icons/Easter_Fun_2023_Event_Easter_Airport_Skin.png",
      "Sweet": "/game-icons/Sweet_Birthday_Event_Sugary_Airport_Skin.png",
      "Ireland": "/game-icons/Irish_Journey_Event_Rainbows_End_Airport_Skin.png",
      "Fashion": "/game-icons/Fashion_Pass_Event_Fashion_Airport_Skin.png",
      "Classic Music": "/game-icons/Music_Festival_Event_Symphony_Airport_Skin.png",
      "Arab": "/game-icons/Arabian_Pass_Event_Arabian_Airport_Skin.png",
      "All Inclusive": "/game-icons/Beach_Vacation_Event_2024_Five-Star_Airport_Skin.png",
      "Carnival 70": "/game-icons/Festival_Airport.png"
    },
    "Helicopter": {
      "Robot": "/game-icons/Helicopter.png",
      "Sleigh": "/game-icons/Santas_Sleigh.png",
      "Sleigh Alt": "/game-icons/Santas_Helpers_Sleigh.png",
      "Travel": "/game-icons/Private_Helicopter.png",
      "UFO": "/game-icons/Flying_Saucer.png",
      "Harvest": "/game-icons/Eggplant_Helicopter_Skin.png",
      "Gatsby": "/game-icons/Ballroom_Adventure_Event_Festive_Helicopter_Skin.png",
      "Sport": "/game-icons/Sports_Marathon_Event_2023_Helicycle.png",
      "Halloween 2023": "/game-icons/Fairytale_Kingdom_2023_Pumpkin_Helicopter.png",
      "Brazil": "/game-icons/Brazilian_Carnival_Event_Feathery_Helicopter_Skin.png",
      "Easter 2024": "/game-icons/Easter_Adventure_Event_2024_Egg_Chopper_Skin.png",
      "Atlantis": "/game-icons/Treasures_of_Atlantis_Event_Flying_Bathyscaphe_Skin.png",
      "Pirate 2024": "/game-icons/Pirate_Adventure_Event_Pirate_Helicopter_Skin.png",
      "Christmas 67": "/game-icons/Christmas_Pass_Event_Christmas_Helicopter_Skin.png",
      "Disco": "/game-icons/Disco_Pass_Event_Disco_Helicopter_Skin.png",
      "Astro": "/game-icons/Astro_Pass_Event_Astro_Helicopter_Skin.png"
    },
    "HelicopterPlace": {
      "UFO": "/game-icons/Flying_Saucer_Hangar.png",
      "Robot": "/game-icons/Helicopter_Pad.png",
      "Sleigh": "/game-icons/Sleigh_Parking_Lot.png",
      "Resort": "/game-icons/Five-Star_Helipad.png",
      "Travel": "/game-icons/Private_Helipad.png",
      "Harvest": "/game-icons/Veggie_Helipad_Skin.png",
      "Gatsby": "/game-icons/Ballroom_Adventure_Event_Ballroom_Helipad_Skin.png",
      "Sport": "/game-icons/Sports_Marathon_Event_2023_Fitness_Pad.png",
      "Brazil": "/game-icons/Brazilian_Carnival_Event_Carnival_Platform_Skin.png",
      "Easter 2024": "/game-icons/Easter_Adventure_Event_2024_Easter_Helipad_Skin.png",
      "Pirate 2024": "/game-icons/Pirate_Adventure_Event_Pirate_Helipad_Skin.png",
      "Christmas 67": "/game-icons/Christmas_Pass_Event_Christmas_Helipad_Skin.png",
      "Astro": "/game-icons/Astro_Pass_Event_Astro_Helipad_Skin.png",
      "Disco": "/game-icons/Disco_Pass_Event_Disco_Helipad_Skin.png"
    },
    "Ship": {
      "Paris": "/game-icons/Town_Port.png",
      "Halloween 2022": "/game-icons/Haunted_Halloween_Ghost_Ship_Skin.png",
      "Valentine's Day": "/game-icons/Love_Fever_Event_2023_Love_Boat.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2024_Dragon_Boat_Skin.png",
      "Wild West 2024": "/game-icons/Wild_Wild_West_Event_River_Steamboat_Skin.png",
      "Birthday 2024": "/game-icons/Sweet_Birthday_Event_2024_Sweet_Boat_Skin.png",
      "Egypt": "/game-icons/Egyptian_Adventure_Event_Egyptian-Theme_Ship_Skin.png",
      "Japan": "/game-icons/Japanese_Pass_Event_Japanese_Ship_Skin.png",
      "Knight": "/game-icons/Knight_Pass_Event_Knight_Ship_Skin.png",
      "Hellas (Greece)": "/game-icons/Sturdy_Drakkar.png",
      "Venice": "/game-icons/Merchant_Cruise.png"
    },
    "Harbor": {
      "Halloween 2022": "/game-icons/Haunted_Halloween_Ghost_Port_Skin.png",
      "Valentine's Day": "/game-icons/Love_Fever_Event_2023_Romantic_Harbor.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2024_Lantern_Harbor_Skin.png",
      "Wild West 2024": "/game-icons/Wild_Wild_West_Event_Saloon_on_the_Water_Skin.png",
      "Birthday 2024": "/game-icons/Sweet_Birthday_Event_2024_Candy_Port_Skin.png",
      "Egypt": "/game-icons/Egyptian_Adventure_Event_Egyptian-Theme_Port_Skin.png",
      "Japan": "/game-icons/Japanese_Pass_Event_Japanese_Port_Skin.png",
      "Knight": "/game-icons/Knight_Pass_Event_Knight_Port_Skin.png",
      "Christmas 2023": "/game-icons/Sweet_Port_Skin.png",
      "Hellas (Greece)": "/game-icons/Viking_Harbor.png",
      "Venice": "/game-icons/Equatorial_Port.png",
      "Paris": "/game-icons/Town_Port.png",
      "Surf 77": "/game-icons/Vacation_Pass_Event_Vacation_Port_Skin.png"
    },
    "Cow": {
      "Movie": "/game-icons/Dazzling_Cow.png",
      "Valentine": "/game-icons/Romantic_Cow.png",
      "Sweet": "/game-icons/Dreamy_Cow.png",
      "Halloween 2023": "/game-icons/Incognito_Cow.png",
      "Spy": "/game-icons/Incognito_Cow.png"
    },
    "Chicken": {
      "Travel": "/game-icons/Chipper_Chicken.png",
      "Sport": "/game-icons/Chipper_Chicken.png",
      "Sweet": "/game-icons/Chipper_Chicken.png"
    },
    "Sheep": {
      "Halloween 2022": "/game-icons/Stellar_Sheep.png",
      "Sweet": "/game-icons/Affectionate_Sheep.png",
      "Detective": "/game-icons/Detective_Stories_Event_2023_The_Sheep_of_the_Baa-skervilles.png"
    },
    "Pig": {
      "Chinese New Year": "/game-icons/Dexterous_Piggy.png"
    },
    "Fortress": {
      "Pirate 1": "/game-icons/Pirate_Harbor.png",
      "Pirate 2": "/game-icons/Pirate_Galleon.png",
      "Paris": "/game-icons/Sultans_Palace.png",
      "Halloween 2021 A": "/game-icons/Vampire_Party_Event_Haunted_Tower_Skin.png",
      "Halloween 2021 B": "/game-icons/Vampire_Party_Event_Haunted_Tower_Skin.png",
      "Christmas": "/game-icons/Magical_Christmas_Event_2022_Santas_Residence_Skin.png",
      "Gatsby 1": "/game-icons/Fairytale_Kingdom_2023_Royal_Palace.png",
      "Atlantis": "/game-icons/Treasures_of_Atlantis_Event_Underwater_Palace_Skin.png"
    }
  },
  "groups": {
    "Train": "/game-icons/Christmas_Train_Skin.png",
    "TrainStation": "/game-icons/Train_Station_Skin.png",
    "Airplane": "/game-icons/Plane.png",
    "Airport": "/game-icons/Airport_Skin.png",
    "Helicopter": "/game-icons/Helicopter.png",
    "HelicopterPlace": "/game-icons/Helicopter_Pad.png",
    "Ship": "/game-icons/Flying_ship.png",
    "Harbor": "/game-icons/Town_Port.png",
    "Cow": "/game-icons/Dazzling_Cow.png",
    "Chicken": "/game-icons/Chipper_Chicken.png",
    "Sheep": "/game-icons/Affectionate_Sheep.png",
    "Pig": "/game-icons/Dexterous_Piggy.png",
    "Fortress": "/game-icons/Fairytale_Kingdom_2023_Royal_Palace.png",
    "Materials": "/game-icons/Bricks.png",
    "Tools": "/game-icons/Axe.png",
    "Match3 Boosts": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png",
    "Coupons": "/game-icons/Expansion_Coupon.png",
    "Boosts": "/game-icons/Advanced_Farming_Booster.png",
    "Styles": "/game-icons/Style_Festival_Banner.png",
    "Themes": "/game-icons/Style_Neon.png",
    "Frames": "/game-icons/Frame_1.png",
    "ExpRanks": "/game-icons/Title_1.png",
    "Gems": "/game-icons/Gems.png",
    "Orders": "/game-icons/Game_Token.png",
    "Match3": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png"
  },
  "decorByLabel": {
    "Christmas Urban tree": "/game-icons/Christmas_Tree.png",
    "Christmas fence": "/game-icons/Christmas_Fence.png",
    "Santa Sleigh": "/game-icons/Santas_Sleigh.png",
    "SpecialBeauty BeePilot": "/game-icons/Bee_Pilot.png",
    "SpecialBeauty GiantWatermelon": "/game-icons/Giant_Watermelon.png",
    "SpecialBeauty WaterTower": "/game-icons/Water_Tower.png",
    "SpecialBeauty firerooster": "/game-icons/Fire_Rooster.png",
    "SpecialBeauty seahorse": "/game-icons/Sea_Horse.png",
    "beauty Flower gates": "/game-icons/Flower_Gate.png",
    "beauty Gong": "/game-icons/Gong.png",
    "beauty candy bridge": "/game-icons/Candy_Bridge.png",
    "beauty candy tree": "/game-icons/Candy_Tree.png",
    "beauty confectioner cow": "/game-icons/Confectioner_Cow.png",
    "beauty elephants": "/game-icons/Elephant.png",
    "beauty flyingship": "/game-icons/Flying_ship.png",
    "beauty gondola": "/game-icons/Gondola.png",
    "beauty mammoth": "/game-icons/Mammoth.png",
    "beauty peacock statue": "/game-icons/Peacock_Statue.png",
    "beauty pine tree": "/game-icons/Pine_Tree.png",
    "beauty playground2": "/game-icons/Playground.png",
    "beauty snowfortress": "/game-icons/Snow_Fortress.png",
    "beauty submarine": "/game-icons/Submarine.png",
    "beauty treasure chest": "/game-icons/Treasure_Chest.png",
    "cactus": "/game-icons/Cactus.png",
    "eifel tower": "/game-icons/Eiffel_Tower.png",
    "flag": "/game-icons/Flag.png",
    "floating lanterns": "/game-icons/Floating_Lanterns.png",
    "flower fence": "/game-icons/Flower_Fence.png",
    "gravelroad": "/game-icons/Gravel_Road.png",
    "groundroad": "/game-icons/Ground_Road.png",
    "hedge": "/game-icons/Hedge.png",
    "ice Dragon": "/game-icons/Ice_Dragon.png",
    "love bridge": "/game-icons/Love_Bridge.png",
    "petronas": "/game-icons/Petronas.png",
    "playground": "/game-icons/Playground.png",
    "pumpkinrace": "/game-icons/Pumpkin_Race.png",
    "sail Hotel": "/game-icons/Sail_Hotel.png",
    "scarecrow": "/game-icons/Scarecrow.png",
    "spacegarden": "/game-icons/Space_Garden.png",
    "water": "/game-icons/Water.png",
    "well": "/game-icons/Well.png",
    "wildpark": "/game-icons/Wild_Park.png",
    "yellow roses": "/game-icons/Yellow_Roses.png",
    "Christmas GingerbreadMan": "/game-icons/Gingerbread_Statue.png",
    "Christmas Santas Reinde": "/game-icons/Santas_Reindeer.png",
    "Christmas Snow fortress": "/game-icons/Snow_Fortress.png",
    "Christmas angel": "/game-icons/Ice_Angel.png",
    "Tower of Pisa": "/game-icons/Leaning_Tower_of_Pisa.png",
    "asphalt": "/game-icons/Asphalt_Road.png",
    "crocodile": "/game-icons/Crocodile_Statue.png",
    "flamingo": "/game-icons/Flamingo_Statue.png",
    "gorilla": "/game-icons/Gorilla_Statue.png",
    "koala": "/game-icons/Koala_Statue.png",
    "lion": "/game-icons/Lion_Statue.png",
    "panda": "/game-icons/Panda_Statue.png",
    "penguin": "/game-icons/Penguin_Statue.png",
    "swan": "/game-icons/Swan_Statue.png",
    "tiger": "/game-icons/Crouching_Tiger_Statue.png",
    "zebra": "/game-icons/Zebra_Statue.png",
    "Hot Dog Swing": "/game-icons/Hot_Dog_Swings_1.png"
  },
  "profileByLabel": {
    "Badge 1": "/game-icons/Badge_1.png",
    "Badge 10": "/game-icons/Badge_10.png",
    "Badge 11": "/game-icons/Badge_11.png",
    "Badge 12": "/game-icons/Badge_12.png",
    "Badge 13": "/game-icons/Badge_13.png",
    "Badge 14": "/game-icons/Badge_14.png",
    "Badge 15": "/game-icons/Badge_15.png",
    "Badge 16": "/game-icons/Badge_16.png",
    "Badge 2": "/game-icons/Badge_2.png",
    "Badge 3": "/game-icons/Badge_3.png",
    "Badge 4": "/game-icons/Badge_4.png",
    "Badge 5": "/game-icons/Badge_5.png",
    "Badge 6": "/game-icons/Badge_6.png",
    "Badge 7": "/game-icons/Badge_7.png",
    "Badge 8": "/game-icons/Badge_8.png",
    "Badge 9": "/game-icons/Badge_9.png",
    "Frame 1": "/game-icons/Frame_1.png",
    "Frame 10": "/game-icons/Frame_10.png",
    "Frame 11": "/game-icons/Frame_11.png",
    "Frame 12": "/game-icons/Frame_12.png",
    "Frame 13": "/game-icons/Frame_13.png",
    "Frame 14": "/game-icons/Frame_14.png",
    "Frame 15": "/game-icons/Frame_15.png",
    "Frame 2": "/game-icons/Frame_2.png",
    "Frame 3": "/game-icons/Frame_3.png",
    "Frame 4": "/game-icons/Frame_4.png",
    "Frame 5": "/game-icons/Frame_5.png",
    "Frame 6": "/game-icons/Frame_6.png",
    "Frame 7": "/game-icons/Frame_7.png",
    "Frame 8": "/game-icons/Frame_8.png",
    "Frame 9": "/game-icons/Frame_9.png",
    "Title 1": "/game-icons/Title_1.png",
    "Title 10": "/game-icons/Title_10.png",
    "Title 11": "/game-icons/Title_11.png",
    "Title 12": "/game-icons/Title_12.png",
    "Title 13": "/game-icons/Title_13.png",
    "Title 14": "/game-icons/Title_14.png",
    "Title 15": "/game-icons/Title_15.png",
    "Title 16": "/game-icons/Title_16.png",
    "Title 17": "/game-icons/Title_17.png",
    "Title 18": "/game-icons/Title_18.png",
    "Title 19": "/game-icons/Title_19.png",
    "Title 2": "/game-icons/Title_2.png",
    "Title 20": "/game-icons/Title_20.png",
    "Title 3": "/game-icons/Title_3.png",
    "Title 4": "/game-icons/Title_4.png",
    "Title 5": "/game-icons/Title_5.png",
    "Title 6": "/game-icons/Title_6.png",
    "Title 7": "/game-icons/Title_7.png",
    "Title 8": "/game-icons/Title_8.png",
    "Title 9": "/game-icons/Title_9.png",
    "Festival": "/game-icons/Style_Festival.png"
  },
  "gemById": {
    "Gem 1": "/game-icons/Gem1.webp",
    "Gem 2": "/game-icons/Gem2.webp",
    "Gem 3": "/game-icons/Gem3.webp"
  },
  "stickerById": {
    "sp1": "/game-icons/Sticker_001.png",
    "sp4": "/game-icons/Sticker_002.png",
    "sp5": "/game-icons/Sticker_003.png",
    "sp6": "/game-icons/Sticker_004.png",
    "sp7": "/game-icons/Sticker_005.png",
    "sp8": "/game-icons/Sticker_006.png",
    "sp9": "/game-icons/Sticker_007.png",
    "sp11": "/game-icons/Sticker_008.png",
    "sp12": "/game-icons/Sticker_009.png",
    "sp10": "/game-icons/Sticker_010.png",
    "sp15": "/game-icons/Sticker_011.png",
    "sp14": "/game-icons/Sticker_012.png",
    "sp13": "/game-icons/Sticker_013.png",
    "sp17": "/game-icons/Sticker_014.png",
    "sp16": "/game-icons/Sticker_015.png",
    "sp18": "/game-icons/Sticker_016.png",
    "v1": "/game-icons/Sticker_017.png",
    "v2": "/game-icons/Sticker_018.png",
    "v3": "/game-icons/Sticker_019.png",
    "sp21": "/game-icons/Sticker_020.png",
    "sp20": "/game-icons/Sticker_021.png",
    "sp19": "/game-icons/Sticker_022.png",
    "sp22": "/game-icons/Sticker_023.png",
    "sp24": "/game-icons/Sticker_024.png",
    "sp23": "/game-icons/Sticker_025.png",
    "st1": "/game-icons/Sticker_026.png",
    "st3": "/game-icons/Sticker_027.png",
    "st2": "/game-icons/Sticker_028.png",
    "sp25": "/game-icons/Sticker_029.png",
    "sp27": "/game-icons/Sticker_030.png",
    "sp26": "/game-icons/Sticker_031.png",
    "st7": "/game-icons/Sticker_032.png",
    "st11": "/game-icons/Sticker_033.png",
    "st15": "/game-icons/Sticker_034.png",
    "st17": "/game-icons/Sticker_035.png",
    "st23": "/game-icons/Sticker_036.png",
    "st22": "/game-icons/Sticker_037.png",
    "st26": "/game-icons/Sticker_038.png",
    "st25": "/game-icons/Sticker_039.png",
    "st24": "/game-icons/Sticker_040.png",
    "st28": "/game-icons/Sticker_041.png",
    "st27": "/game-icons/Sticker_042.png",
    "st30": "/game-icons/Sticker_043.png",
    "st29": "/game-icons/Sticker_044.png",
    "st32": "/game-icons/Sticker_045.png",
    "st31": "/game-icons/Sticker_046.png",
    "st34": "/game-icons/Sticker_047.png",
    "st35": "/game-icons/Sticker_048.png",
    "st36": "/game-icons/Sticker_049.png",
    "st38": "/game-icons/Sticker_050.png",
    "st37": "/game-icons/Sticker_051.png",
    "st39": "/game-icons/Sticker_052.png"
  }
} as const;

export function iconForStat(key: string): string | null {
  return (GAME_ICON_MAP.stats as Record<string, string>)[key] ?? null;
}

export function iconForItemLabel(label: string): string | null {
  return (GAME_ICON_MAP.itemsByLabel as Record<string, string>)[label] ?? null;
}

export function iconForBarn(id: string): string | null {
  return (GAME_ICON_MAP.barn as Record<string, string>)[id] ?? null;
}

export function iconForGroup(groupId: string): string | null {
  return (GAME_ICON_MAP.groups as Record<string, string>)[groupId] ?? null;
}

export function iconForSkin(groupId: string, label: string): string | null {
  const g = (GAME_ICON_MAP.skinsByGroupLabel as Record<string, Record<string, string>>)[groupId];
  return g?.[label] ?? null;
}

export function iconForDecorLabel(label: string): string | null {
  return (GAME_ICON_MAP.decorByLabel as Record<string, string>)[label] ?? null;
}

export function iconForProfileLabel(label: string): string | null {
  return (GAME_ICON_MAP.profileByLabel as Record<string, string>)[label]
    ?? (GAME_ICON_MAP.itemsByLabel as Record<string, string>)[label]
    ?? null;
}

export function iconForSticker(id: string): string | null {
  return (GAME_ICON_MAP.stickerById as Record<string, string>)[id] ?? null;
}

export function iconForGem(id: string): string | null {
  return (GAME_ICON_MAP.gemById as Record<string, string>)[id]
    ?? (GAME_ICON_MAP.gemById as Record<string, string>)[id.toLowerCase().replace(/\s+/g, "")]
    ?? null;
}
