/** Auto-mapped original Township icons. Only confident matches. */
export const GAME_ICON_MAP = {
  "stats": {
    "spentCash": "/game-icons/spentCash.webp",
    "earnedCash": "/game-icons/earnedCash.webp",
    "EarnedCoins": "/game-icons/EarnedCoins.webp",
    "timeInGame": "/game-icons/timeInGame.webp",
    "WareHouseCashUpgrade": "/game-icons/WareHouseCashUpgrade.webp",
    "Match3Lives_infTime": "/game-icons/Match3Lives_infTime.webp",

    "tca": "/game-icons/T-cash.png",
    "coi": "/game-icons/Coins.png",
    "lvl": "/game-icons/Level.png",
    "win": "/game-icons/First_attempt_win.png",
    "liv": "/game-icons/Lives_send.png",
    "reg": "/game-icons/Regatta.png",
    "hlp": "/game-icons/help.png",
    "exp": "/game-icons/Energy.png",
    "m3l": "/game-icons/M3_Level.png",
    "match3Life": "/game-icons/Lives_x3.png",
    "residents": "/game-icons/Residents.png",
    "crd": "/game-icons/Cards.png",
    "wheatCounter": "/game-icons/Wheat.png",
    "defaultOrdersCount": "/game-icons/Game_Token.png"
  },
  "itemsByLabel": {
    "Brick": "/game-icons/Bricks.png",
    "Glass": "/game-icons/Glass.png",
    "Slab": "/game-icons/Slab.png",
    "Pickaxe": "/game-icons/Pickaxe.png",
    "Axe": "/game-icons/Axe.png",
    "TNT": "/game-icons/TNT.png",
    "Jackhammer": "/game-icons/Jackhammer.png",
    "Power Saw": "/game-icons/Electric_Saw.png",
    "Drill": "/game-icons/Drill.png",
    "Rainbow Ball": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png",
    "Bomb + Rocket": "/game-icons/Match-3_Activate_the_Rocket_Power-up.png",
    "Bomb": "/game-icons/Color_Splash_Bomb.png",
    "Mallet": "/game-icons/Hammer.png",
    "Island Probability": "/game-icons/BoostProbabilityIslands.webp",
    "Storage Capacity": "/game-icons/BoostStorageCapacity.webp",
    "Market Time": "/game-icons/BoostTimeMarket.webp",
    "Speed Up Order": "/game-icons/BoostSpeedUpOrder.webp",
    "Speed Up Ships": "/game-icons/BoostSpeedUpShips.webp",
    "Factory Time": "/game-icons/BoostTimeFactory.webp",
    "Smeltery Time": "/game-icons/BoostTimeSmeltery.webp",
    "Lantern Mine": "/game-icons/BoostLanternMine.webp",
    "Speed Up Harvest": "/game-icons/BoostSpeedUpHarvest.webp",
    "Money Order": "/game-icons/BoostMoneyOrder.webp",
    "Speed Up Trains": "/game-icons/BoostSpeedUpTrains.webp",
    "Airport Coins": "/game-icons/BoostAirportCoins.webp",
    "Clan Help Request": "/game-icons/BoostClanHelpRequest.webp",
    "Product Farm": "/game-icons/BoostProductFarm.webp",
    "Product Harvest": "/game-icons/BoostProductHarvest.webp",
    "Double Factory": "/game-icons/BoostDoubleFactory.webp",
    "Speed Up Dealer": "/game-icons/BoostSpeedUpDealer.webp",
    "Zoo Hearts": "/game-icons/Zoo_Hearts.webp",
    "Max Donate": "/game-icons/Max_Donate.webp",
    "Airplane": "/game-icons/Airplane.webp",
    "Line": "/game-icons/Line.webp",
    "Vertical Line": "/game-icons/Vertical_Line.webp",
    "Horizontal Line": "/game-icons/Horizontal_Line.webp",
    "Reshuffle": "/game-icons/Reshuffle.webp",
    "Factory Upgrade Coupon": "/game-icons/Factory_Upgrade_Coupon.webp",
    "Island Upgrade Coupon": "/game-icons/Island_Upgrade_Coupon.webp",
    "Hire Dealer Coupon": "/game-icons/Dealer_Coupon.webp",
    "Barn Capacity Coupon": "/game-icons/Barn_Upgrade_Coupon.webp",
    "Expansion Coupon": "/game-icons/Expansion_Coupon.webp",
    "Load Train/Airport Coupon": "/game-icons/Load_Coupon.webp",
    "Train Upgrade Coupon": "/game-icons/Train_Coupon.webp",
    "Badge 1": "/game-icons/Badge_1.png",
    "Badge 10": "/game-icons/Badge_10.png",
    "Badge 11": "/game-icons/Badge_11.png",
    "Badge 12": "/game-icons/Badge_12.png",
    "Badge 13": "/game-icons/Badge_13.png",
    "Badge 14": "/game-icons/Badge_14.png",
    "Badge 15": "/game-icons/Badge_15.png",
    "Badge 16": "/game-icons/Badge_16.png",
    "Badge 2": "/game-icons/Badge_2.png",
    "Badge 3": "/game-icons/Badge_3.png",
    "Badge 4": "/game-icons/Badge_4.png",
    "Badge 5": "/game-icons/Badge_5.png",
    "Badge 6": "/game-icons/Badge_6.png",
    "Badge 7": "/game-icons/Badge_7.png",
    "Badge 8": "/game-icons/Badge_8.png",
    "Badge 9": "/game-icons/Badge_9.png",
    "Frame 1": "/game-icons/Frame_1.png",
    "Frame 10": "/game-icons/Frame_10.png",
    "Frame 11": "/game-icons/Frame_11.png",
    "Frame 12": "/game-icons/Frame_12.png",
    "Frame 13": "/game-icons/Frame_13.png",
    "Frame 14": "/game-icons/Frame_14.png",
    "Frame 15": "/game-icons/Frame_15.png",
    "Frame 2": "/game-icons/Frame_2.png",
    "Frame 3": "/game-icons/Frame_3.png",
    "Frame 4": "/game-icons/Frame_4.png",
    "Frame 5": "/game-icons/Frame_5.png",
    "Frame 6": "/game-icons/Frame_6.png",
    "Frame 7": "/game-icons/Frame_7.png",
    "Frame 8": "/game-icons/Frame_8.png",
    "Frame 9": "/game-icons/Frame_9.png",
    "Title 1": "/game-icons/Title_1.png",
    "Title 10": "/game-icons/Title_10.png",
    "Title 11": "/game-icons/Title_11.png",
    "Title 12": "/game-icons/Title_12.png",
    "Title 13": "/game-icons/Title_13.png",
    "Title 14": "/game-icons/Title_14.png",
    "Title 15": "/game-icons/Title_15.png",
    "Title 16": "/game-icons/Title_16.png",
    "Title 17": "/game-icons/Title_17.png",
    "Title 18": "/game-icons/Title_18.png",
    "Title 19": "/game-icons/Title_19.png",
    "Title 2": "/game-icons/Title_2.png",
    "Title 20": "/game-icons/Title_20.png",
    "Title 3": "/game-icons/Title_3.png",
    "Title 4": "/game-icons/Title_4.png",
    "Title 5": "/game-icons/Title_5.png",
    "Title 6": "/game-icons/Title_6.png",
    "Title 7": "/game-icons/Title_7.png",
    "Title 8": "/game-icons/Title_8.png",
    "Title 9": "/game-icons/Title_9.png",
    "Festival": "/game-icons/Style_Festival_Banner.png",
    "Cooking": "/game-icons/Style_Cooking.png",
    "Easter": "/game-icons/Style_Easter.png",
    "Neon": "/game-icons/Style_Neon.png",
    "Underwater Violet": "/game-icons/Style_Underwater_Violet.png",
    "Style 6": "/game-icons/Style_Gold.png",
    "Bubble": "/game-icons/Soap_Bubbles.png"
  },
  "barn": {
    "aloeLeaves": "/barn-goods/aloeLeaves.webp",
    "basketbouquet": "/barn-goods/basketbouquet.webp",
    "carrot_hotdog": "/barn-goods/carrot_hotdog.webp",
    "coconut_raf": "/barn-goods/coconut_raf.webp",
    "driedMushrooms": "/barn-goods/driedMushrooms.webp",
    "fish_chips": "/barn-goods/fish_chips.webp",
    "fishburger": "/barn-goods/fishburger.webp",
    "fried_fish": "/barn-goods/fried_fish.webp",
    "glazedbacon": "/barn-goods/glazedbacon.webp",
    "grapes_jam": "/barn-goods/grapes_jam.webp",
    "hat": "/barn-goods/hat.webp",
    "honeycandy": "/barn-goods/honeycandy.webp",
    "hot_dog": "/barn-goods/hot_dog.webp",
    "hummus": "/barn-goods/hummus.webp",
    "icecream": "/barn-goods/icecream.webp",
    "lobster_newburg": "/barn-goods/lobster_newburg.webp",
    "lobster_nigiri": "/barn-goods/lobster_nigiri.webp",
    "lollipop": "/barn-goods/lollipop.webp",
    "milkshake": "/barn-goods/milkshake.webp",
    "mintcake": "/barn-goods/mintcake.webp",
    "mintchocolateicecream": "/barn-goods/mintchocolateicecream.webp",
    "minticetea": "/barn-goods/minticetea.webp",
    "mintlollipops": "/barn-goods/mintlollipops.webp",
    "muffin": "/barn-goods/muffin.webp",
    "mug": "/barn-goods/mug.webp",
    "mushroom_jam": "/barn-goods/mushroom_jam.webp",
    "mushroomPie": "/barn-goods/mushroomPie.webp",
    "mushroomSalad": "/barn-goods/mushroomSalad.webp",
    "mushroomSoup": "/barn-goods/mushroomSoup.webp",
    "mushroomfeed": "/barn-goods/mushroomfeed.webp",
    "newbackpack": "/barn-goods/newbackpack.webp",
    "oolong": "/barn-goods/oolong.webp",
    "peach_jam": "/barn-goods/peach_jam.webp",
    "peachyogurt": "/barn-goods/peachyogurt.webp",
    "pearlneck": "/barn-goods/pearlneck.webp",
    "pineapplesorbet": "/barn-goods/pineapplesorbet.webp",
    "plum_jam": "/barn-goods/plum_jam.webp",
    "popcorn": "/barn-goods/popcorn.webp",
    "potatobread": "/barn-goods/potatobread.webp",
    "puffedrice": "/barn-goods/puffedrice.webp",
    "rice_casserole": "/barn-goods/rice_casserole.webp",
    "rice_noodle": "/barn-goods/rice_noodle.webp",
    "roseJam": "/barn-goods/roseJam.webp",
    "roseSeed": "/barn-goods/roseSeed.webp",
    "roseSorbet": "/barn-goods/roseSorbet.webp",
    "rosetea": "/barn-goods/rosetea.webp",
    "rubber": "/barn-goods/rubber.webp",
    "scallopskew": "/barn-goods/scallopskew.webp",
    "scallopsushi": "/barn-goods/scallopsushi.webp",
    "seaweedsalad": "/barn-goods/seaweedsalad.webp",
    "shirt": "/barn-goods/shirt.webp",
    "soup": "/barn-goods/soup.webp",
    "soymilk": "/barn-goods/soymilk.webp",
    "strawberrycake": "/barn-goods/strawberrycake.webp",
    "table": "/barn-goods/table.webp",
    "teacoffeebouquet": "/barn-goods/teacoffeebouquet.webp",
    "toys": "/barn-goods/toys.webp",
    "watermelon_fresh": "/barn-goods/watermelon_fresh.webp",
    "whitetea": "/barn-goods/whitetea.webp",
    "woolfabric": "/barn-goods/woolfabric.webp",
    "wheel": "/barn-goods/wheel.webp",

    "wheat": "/game-icons/Wheat.png",
    "corn": "/game-icons/Corn.png",
    "carrot": "/game-icons/Carrot.png",
    "sugarcane": "/game-icons/Sugarcane.png",
    "milk": "/game-icons/Milk.png",
    "egg": "/game-icons/Egg.png",
    "cotton": "/game-icons/Cotton.png",
    "paint": "/game-icons/Paint.png",
    "honey": "/game-icons/Honeycombs.png",
    "wool": "/game-icons/Wool.png",
    "bread": "/game-icons/Bread.PNG",
    "cookie": "/game-icons/Easter_Cookie.png",
    "clover": "/game-icons/Clover.png",
    "fabric": "/game-icons/Silk.png",
    "BronzeBullion": "/game-icons/Bronze_Ingot.png",
    "SilverBullion": "/game-icons/Silver_Ingot.png",
    "GoldBullion": "/game-icons/Gold_Ingot.png",
    "PlatinumBullion": "/game-icons/Platinum_Ingot.png",
    "accordion": "/game-icons/Accordion.png",
    "aloe": "/game-icons/Aloe.png",
    "apple": "/game-icons/Apple.png",
    "appletea": "/game-icons/Apple_Tea.png",
    "bacon": "/game-icons/Bacon.png",
    "banana": "/game-icons/Banana.png",
    "basket": "/game-icons/Basket.png",
    "blacktea": "/game-icons/Black_Tea.png",
    "cacao": "/game-icons/Cacao.png",
    "candy": "/game-icons/Candy.png",
    "caramel": "/game-icons/Caramel_.png",
    "clay": "/game-icons/Clay.png",
    "coconut": "/game-icons/Coconut.png",
    "coffee": "/game-icons/Coffee.png",
    "cottonCandy": "/game-icons/Cotton_Candy.png",
    "cutlery": "/game-icons/Cutlery.png",
    "downFeather": "/game-icons/Down_Feather.png",
    "falafel": "/game-icons/Falafel.png",
    "fish": "/game-icons/Fish.png",
    "gardengnome": "/game-icons/Garden_Gnome.png",
    "grapes": "/game-icons/Grapes.png",
    "jasmine": "/game-icons/Jasmine.png",
    "lasagna": "/game-icons/Lasagna.png",
    "lavender": "/game-icons/Lavender.png",
    "lei": "/game-icons/Lei.png",
    "lobster": "/game-icons/Lobster.png",
    "mint": "/game-icons/Mint.png",
    "misosoup": "/game-icons/Miso_Soup.png",
    "mushroom": "/game-icons/Mushroom.png",
    "oliveoil": "/game-icons/Olive_Oil.png",
    "peach": "/game-icons/Peach.png",
    "pearl": "/game-icons/Pearl.png",
    "pepper": "/game-icons/Pepper.png",
    "pineapple": "/game-icons/Pineapple.png",
    "plum": "/game-icons/Plum.png",
    "potato": "/game-icons/Potato.png",
    "ravioli": "/game-icons/Ravioli.png",
    "rice": "/game-icons/Rice.png",
    "rubberTree": "/game-icons/Rubber_Tree.png",
    "sandals": "/game-icons/Sandals.png",
    "saxophone": "/game-icons/Saxophone.png",
    "scallop": "/game-icons/Scallop.png",
    "seaweed": "/game-icons/Seaweed.png",
    "shrimp": "/game-icons/Shrimp.png",
    "silk": "/game-icons/Silk.png",
    "soapBubbles": "/game-icons/Soap_Bubbles.png",
    "soybean": "/game-icons/Soybean.png",
    "strawberry": "/game-icons/Strawberry.png",
    "suitcase": "/game-icons/Suitcase.png",
    "teapot": "/game-icons/Teapot.png",
    "ukulele": "/game-icons/Ukulele.png",
    "vegancheesecake": "/game-icons/Vegan_Cheesecake.png",
    "waterbowl": "/game-icons/Water_Bowl.png",
    "watermelon": "/game-icons/Watermelon.png",
"bigFeather": "/barn-goods/bigFeather.webp",
    "book": "/barn-goods/book.webp",
    "butter": "/barn-goods/butter.webp",
    "candystick": "/barn-goods/candystick.webp",
    "cheese": "/barn-goods/cheese.webp",
    "cork": "/barn-goods/cork.webp",
    "earrings": "/barn-goods/earrings.webp",
    "honeycomb": "/barn-goods/honeycomb.webp",
    "olive": "/barn-goods/olive.webp",
    "pinata": "/barn-goods/pinata.webp",
    "cream": "/barn-goods/cream.webp",
    "custard": "/barn-goods/custard.webp",
    "glue": "/barn-goods/glue.webp",
    "gyoza": "/barn-goods/gyoza.webp",
    "jellybeans": "/barn-goods/jellybeans.webp",
    "ketchup": "/barn-goods/ketchup.webp",
    "mango1": "/barn-goods/mango1.webp",
    "nachos": "/barn-goods/nachos.webp",
    "nylonthread": "/barn-goods/nylonthread.webp",
    "papertowel": "/barn-goods/papertowel.webp",
    "peanut": "/barn-goods/peanut.webp",
    "plasticbottle": "/barn-goods/plasticbottle.webp",
    "sandwich": "/barn-goods/sandwich.webp",
    "silkfabric": "/barn-goods/silkfabric.webp",
    "strawberry_jam": "/barn-goods/strawberry_jam.webp",
    "sugar": "/barn-goods/sugar.webp",
    "syrup": "/barn-goods/syrup.webp",
    "teabush": "/barn-goods/teabush.webp",
    "tofu": "/barn-goods/tofu.webp",
    "tomat": "/barn-goods/tomat.webp",
    "watermelon_jam": "/barn-goods/watermelon_jam.webp",
    "yogurt": "/barn-goods/yogurt.webp",
"air_freshener": "/barn-goods/air_freshener.webp",
    "airballoon": "/barn-goods/airballoon.webp",
    "applefresh": "/barn-goods/applefresh.webp",
    "applejam": "/barn-goods/applejam.webp",
    "bacon_eggs": "/barn-goods/bacon_eggs.webp",
    "bagel": "/barn-goods/bagel.webp",
    "baked_lobster": "/barn-goods/baked_lobster.webp",
    "bakedpotatoes": "/barn-goods/bakedpotatoes.webp",
    "ball": "/barn-goods/ball.webp",
    "bananabread": "/barn-goods/bananabread.webp",
    "bathrobeslippers": "/barn-goods/bathrobeslippers.webp",
    "bed": "/barn-goods/bed.webp",
    "beefeed": "/barn-goods/beefeed.webp",
    "boots": "/barn-goods/boots.webp",
    "bouillabaisse": "/barn-goods/bouillabaisse.webp",
    "brownie": "/barn-goods/brownie.webp",
    "bruschetta": "/barn-goods/bruschetta.webp",
    "brush": "/barn-goods/brush.webp",
    "burrito": "/barn-goods/burrito.webp",
    "cappuccino": "/barn-goods/cappuccino.webp",
    "caramelapple": "/barn-goods/caramelapple.webp",
    "carrotcake": "/barn-goods/carrotcake.webp",
    "catlitter": "/barn-goods/catlitter.webp",
    "chair": "/barn-goods/chair.webp",
    "cheeseburger": "/barn-goods/cheeseburger.webp",
    "cheesecake": "/barn-goods/cheesecake.webp",
    "chickenfeed": "/barn-goods/chickenfeed.webp",
    "chips": "/barn-goods/chips.webp",
    "chocolate": "/barn-goods/chocolate.webp",
    "chocolate_smoothie": "/barn-goods/chocolate_smoothie.webp",
    "chocolatecake": "/barn-goods/chocolatecake.webp",
    "clothesline": "/barn-goods/clothesline.webp",
    "coat": "/barn-goods/coat.webp",
    "coconutmacaroon": "/barn-goods/coconutmacaroon.webp",
    "coffeecake": "/barn-goods/coffeecake.webp",
    "cold_tea": "/barn-goods/cold_tea.webp",
    "corn_soup": "/barn-goods/corn_soup.webp",
    "cornchips": "/barn-goods/cornchips.webp",
    "corndog": "/barn-goods/corndog.webp",
    "cottonfabric": "/barn-goods/cottonfabric.webp",
    "couch": "/barn-goods/couch.webp",
    "cowfeed": "/barn-goods/cowfeed.webp",
    "cupcake": "/barn-goods/cupcake.webp",
    "diadem": "/barn-goods/diadem.webp",
    "dispenser": "/barn-goods/dispenser.webp",
    "paper": "/barn-goods/paper.webp",
  },
  "skinsByGroupLabel": {
    "TrainStation": {
      "Default": "/game-icons/Train_Station_Skin.png",
      "Express": "/game-icons/Express_Portal.png",
      "Ghost": "/game-icons/Ghost_Station.png",
      "Disco": "/game-icons/Disco_Station.png",
      "Cowboy": "/game-icons/Cowboy_Station.png",
      "Christmas": "/game-icons/Christmas_Station_Skin.png",
      "Easter": "/game-icons/Easter_Station_Skin.png",
      "Ancient": "/game-icons/Ancient_Settlement.png",
      "Theater": "/game-icons/Theater_Premiere_Event_Theater_Set_Station.png",
      "Chinese": "/game-icons/Lantern_Festival_Event_2023_Chinese_Station_Skin.png",
      "Space": "/game-icons/Martian_Odyssey_Event_2023_Space_Station_Skin.png",
      "Camp": "/game-icons/Forest_Adventure_Event_Training_Camp_Skin.png",
      "Record": "/game-icons/Rock_n_Roll_Festival_Event_Record_Station_Skin.png",
      "Castle": "/game-icons/Brotherhood_of_the_Knights_Event_Castle_Station_Skin.png",
      "Roman": "/game-icons/Italian_Holiday_Event_Roman_Station_Skin.png",
      "Halloween": "/game-icons/Haunted_Halloween_Event_Halloween_Station_Skin.png",
      "Magical": "/game-icons/Magical_Christmas_Event_Christmas_Station_Skin.png",
      "Festival": "/game-icons/Flower_Pass_Event_Flower_Station_Skin.png",
      "Hellas": "/game-icons/Mythic_Pass_Event_Mythic_Station_Skin.png",
      "Gatsby": "/game-icons/Gatsby_Pass_Event_Gatsby_Train_Station_Skin.png"
    },
    "Train": {
      "Christmas": "/game-icons/Christmas_Train_Skin.png",
      "Christmas 2024": "/game-icons/Magical_Christmas_Event_Christmas_Train_Skin.png",
      "Knight": "/game-icons/Brotherhood_of_the_Knights_Event_Knight_Train_Skin.png",
      "Western": "/game-icons/Cowboy_Train.png",
      "Gatsby": "/game-icons/Gatsby_Pass_Event_Gatsby_Train_Skin.png",
      "Halloween 2024": "/game-icons/Haunted_Halloween_Event_Halloween_Train_Skin.png",
      "Easter": "/game-icons/Easter_Express_Train_Skin.png",
      "Rock & Roll": "/game-icons/Disco_Train.png",
      "Festival": "/game-icons/Flower_Pass_Event_Flower_Train_Skin.png",
      "Prehistoric": "/game-icons/Primeval_Express.png",
      "Theatrical": "/game-icons/Theater_Premiere_Event_Theater_Express.png",
      "Mars": "/game-icons/Martian_Odyssey_Event_2023_Mars_Rover_Skin.png",
      "Italy 2024": "/game-icons/Italian_Holiday_Event_Express_Tram_Skin.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2023_Dragon_Train_Skin.png",
      "Ghost": "/game-icons/Ghost_Train.png",
      "Special SP2": "/game-icons/Farm_Express.png",
      "Special SP5": "/game-icons/Thunderbird.png",
      "Special SP8": "/game-icons/Red_Lightning.png",
      "Future 76": "/game-icons/Future_Express.png"
    },
    "Airplane": {
      "Special SP3": "/game-icons/Plane.png",
      "Space": "/game-icons/Ultra_Plane.png",
      "Rock": "/game-icons/Rock_Plane.png",
      "Movie": "/game-icons/A-lister_Jet.png",
      "Halloween 2021": "/game-icons/Ghost_Plane.png",
      "Christmas 2022": "/game-icons/Magical_Christmas_Event_2022_Plane_Skin.png",
      "Easter 2023": "/game-icons/Easter_Fun_2023_Event_Bird_Plane_Skin.png",
      "Sweet": "/game-icons/Sweet_Birthday_Event_Eclair_Plane_Skin.png",
      "Ireland": "/game-icons/Irish_Journey_Event_Lucky_Jet_Skin.png",
      "Fashion": "/game-icons/Fashion_Pass_Event_Fashion_Plane_Skin.png",
      "Classic Music": "/game-icons/Music_Festival_Event_Symphony_Plane_Skin.png",
      "Arab": "/game-icons/Arabian_Pass_Event_Arabian_Plane_Skin.png",
      "Spy": "/game-icons/Spy_Games_Event_Stealth_Aircraft_Skin.png",
      "All Inclusive": "/game-icons/Beach_Vacation_Event_2024_Seaplane_Skin.png",
      "Winter Sport": "/game-icons/Sporty_Winter_Event_Areo_Sleigh_Skin.png"
    },
    "Airport": {
      "Special SP3": "/game-icons/Airport_Skin.png",
      "Space": "/game-icons/Spaceport_Skin.png",
      "Rock": "/game-icons/Rock_Airport.png",
      "Movie": "/game-icons/Cinema_Airport.png",
      "Halloween 2021": "/game-icons/Ghost_Airport.png",
      "Christmas 2022": "/game-icons/Airport_Skin.png",
      "Easter 2023": "/game-icons/Easter_Fun_2023_Event_Easter_Airport_Skin.png",
      "Sweet": "/game-icons/Sweet_Birthday_Event_Sugary_Airport_Skin.png",
      "Ireland": "/game-icons/Irish_Journey_Event_Rainbows_End_Airport_Skin.png",
      "Fashion": "/game-icons/Fashion_Pass_Event_Fashion_Airport_Skin.png",
      "Classic Music": "/game-icons/Music_Festival_Event_Symphony_Airport_Skin.png",
      "Arab": "/game-icons/Arabian_Pass_Event_Arabian_Airport_Skin.png",
      "All Inclusive": "/game-icons/Beach_Vacation_Event_2024_Five-Star_Airport_Skin.png",
      "Carnival 70": "/game-icons/Festival_Airport.png"
    },
    "Helicopter": {
      "Robot": "/game-icons/Helicopter.png",
      "Sleigh": "/game-icons/Santas_Sleigh.png",
      "Sleigh Alt": "/game-icons/Santas_Helpers_Sleigh.png",
      "Travel": "/game-icons/Private_Helicopter.png",
      "UFO": "/game-icons/Flying_Saucer.png",
      "Harvest": "/game-icons/Eggplant_Helicopter_Skin.png",
      "Gatsby": "/game-icons/Ballroom_Adventure_Event_Festive_Helicopter_Skin.png",
      "Sport": "/game-icons/Sports_Marathon_Event_2023_Helicycle.png",
      "Halloween 2023": "/game-icons/Fairytale_Kingdom_2023_Pumpkin_Helicopter.png",
      "Brazil": "/game-icons/Brazilian_Carnival_Event_Feathery_Helicopter_Skin.png",
      "Easter 2024": "/game-icons/Easter_Adventure_Event_2024_Egg_Chopper_Skin.png",
      "Atlantis": "/game-icons/Treasures_of_Atlantis_Event_Flying_Bathyscaphe_Skin.png",
      "Pirate 2024": "/game-icons/Pirate_Adventure_Event_Pirate_Helicopter_Skin.png",
      "Christmas 67": "/game-icons/Christmas_Pass_Event_Christmas_Helicopter_Skin.png",
      "Disco": "/game-icons/Disco_Pass_Event_Disco_Helicopter_Skin.png",
      "Astro": "/game-icons/Astro_Pass_Event_Astro_Helicopter_Skin.png"
    },
    "HelicopterPlace": {
      "UFO": "/game-icons/Flying_Saucer_Hangar.png",
      "Robot": "/game-icons/Helicopter_Pad.png",
      "Sleigh": "/game-icons/Sleigh_Parking_Lot.png",
      "Resort": "/game-icons/Five-Star_Helipad.png",
      "Travel": "/game-icons/Private_Helipad.png",
      "Harvest": "/game-icons/Veggie_Helipad_Skin.png",
      "Gatsby": "/game-icons/Ballroom_Adventure_Event_Ballroom_Helipad_Skin.png",
      "Sport": "/game-icons/Sports_Marathon_Event_2023_Fitness_Pad.png",
      "Brazil": "/game-icons/Brazilian_Carnival_Event_Carnival_Platform_Skin.png",
      "Easter 2024": "/game-icons/Easter_Adventure_Event_2024_Easter_Helipad_Skin.png",
      "Pirate 2024": "/game-icons/Pirate_Adventure_Event_Pirate_Helipad_Skin.png",
      "Christmas 67": "/game-icons/Christmas_Pass_Event_Christmas_Helipad_Skin.png",
      "Astro": "/game-icons/Astro_Pass_Event_Astro_Helipad_Skin.png",
      "Disco": "/game-icons/Disco_Pass_Event_Disco_Helipad_Skin.png"
    },
    "Ship": {
      "Paris": "/game-icons/Town_Port.png",
      "Halloween 2022": "/game-icons/Haunted_Halloween_Ghost_Ship_Skin.png",
      "Valentine's Day": "/game-icons/Love_Fever_Event_2023_Love_Boat.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2024_Dragon_Boat_Skin.png",
      "Wild West 2024": "/game-icons/Wild_Wild_West_Event_River_Steamboat_Skin.png",
      "Birthday 2024": "/game-icons/Sweet_Birthday_Event_2024_Sweet_Boat_Skin.png",
      "Egypt": "/game-icons/Egyptian_Adventure_Event_Egyptian-Theme_Ship_Skin.png",
      "Japan": "/game-icons/Japanese_Pass_Event_Japanese_Ship_Skin.png",
      "Knight": "/game-icons/Knight_Pass_Event_Knight_Ship_Skin.png",
      "Hellas (Greece)": "/game-icons/Sturdy_Drakkar.png",
      "Venice": "/game-icons/Merchant_Cruise.png"
    },
    "Harbor": {
      "Halloween 2022": "/game-icons/Haunted_Halloween_Ghost_Port_Skin.png",
      "Valentine's Day": "/game-icons/Love_Fever_Event_2023_Romantic_Harbor.png",
      "Chinese New Year": "/game-icons/Lantern_Festival_Event_2024_Lantern_Harbor_Skin.png",
      "Wild West 2024": "/game-icons/Wild_Wild_West_Event_Saloon_on_the_Water_Skin.png",
      "Birthday 2024": "/game-icons/Sweet_Birthday_Event_2024_Candy_Port_Skin.png",
      "Egypt": "/game-icons/Egyptian_Adventure_Event_Egyptian-Theme_Port_Skin.png",
      "Japan": "/game-icons/Japanese_Pass_Event_Japanese_Port_Skin.png",
      "Knight": "/game-icons/Knight_Pass_Event_Knight_Port_Skin.png",
      "Christmas 2023": "/game-icons/Sweet_Port_Skin.png",
      "Hellas (Greece)": "/game-icons/Viking_Harbor.png",
      "Venice": "/game-icons/Equatorial_Port.png",
      "Paris": "/game-icons/Town_Port.png",
      "Surf 77": "/game-icons/Vacation_Pass_Event_Vacation_Port_Skin.png"
    },
    "Cow": {
      "Movie": "/game-icons/Dazzling_Cow.png",
      "Valentine": "/game-icons/Romantic_Cow.png",
      "Sweet": "/game-icons/Dreamy_Cow.png",
      "Halloween 2023": "/game-icons/Incognito_Cow.png",
      "Spy": "/game-icons/Incognito_Cow.png"
    },
    "Chicken": {
      "Travel": "/game-icons/Chipper_Chicken.png",
      "Sport": "/game-icons/Chipper_Chicken.png",
      "Sweet": "/game-icons/Chipper_Chicken.png"
    },
    "Sheep": {
      "Halloween 2022": "/game-icons/Stellar_Sheep.png",
      "Sweet": "/game-icons/Affectionate_Sheep.png",
      "Detective": "/game-icons/Detective_Stories_Event_2023_The_Sheep_of_the_Baa-skervilles.png"
    },
    "Pig": {
      "Chinese New Year": "/game-icons/Dexterous_Piggy.png"
    },
    "Fortress": {
      "Pirate 1": "/game-icons/Pirate_Harbor.png",
      "Pirate 2": "/game-icons/Pirate_Galleon.png",
      "Paris": "/game-icons/Sultans_Palace.png",
      "Halloween 2021 A": "/game-icons/Vampire_Party_Event_Haunted_Tower_Skin.png",
      "Halloween 2021 B": "/game-icons/Vampire_Party_Event_Haunted_Tower_Skin.png",
      "Christmas": "/game-icons/Magical_Christmas_Event_2022_Santas_Residence_Skin.png",
      "Gatsby 1": "/game-icons/Fairytale_Kingdom_2023_Royal_Palace.png",
      "Atlantis": "/game-icons/Treasures_of_Atlantis_Event_Underwater_Palace_Skin.png"
    }
  },
  "groups": {
    "Train": "/game-icons/Christmas_Train_Skin.png",
    "TrainStation": "/game-icons/Train_Station_Skin.png",
    "Airplane": "/game-icons/Plane.png",
    "Airport": "/game-icons/Airport_Skin.png",
    "Helicopter": "/game-icons/Helicopter.png",
    "HelicopterPlace": "/game-icons/Helicopter_Pad.png",
    "Ship": "/game-icons/Flying_ship.png",
    "Harbor": "/game-icons/Town_Port.png",
    "Cow": "/game-icons/Dazzling_Cow.png",
    "Chicken": "/game-icons/Chipper_Chicken.png",
    "Sheep": "/game-icons/Affectionate_Sheep.png",
    "Pig": "/game-icons/Dexterous_Piggy.png",
    "Fortress": "/game-icons/Fairytale_Kingdom_2023_Royal_Palace.png",
    "Materials": "/game-icons/Bricks.png",
    "Tools": "/game-icons/Axe.png",
    "Match3 Boosts": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png",
    "Coupons": "/game-icons/Expansion_Coupon.webp",
    "Boosts": "/game-icons/Advanced_Farming_Booster.png",
    "Styles": "/game-icons/Style_Festival_Banner.png",
    "Themes": "/game-icons/Style_Neon.png",
    "Frames": "/game-icons/Frame_1.png",
    "ExpRanks": "/game-icons/Title_1.png",
    "Gems": "/game-icons/Gems.png",
    "Orders": "/game-icons/Game_Token.png",
    "Match3": "/game-icons/Match-3_Activate_the_Rainbow_Ball_Power-up.png"
  },
  "decorByLabel": {
    "Chinese NY Tree": "/game-icons/Chinese_NY_Tree.webp",
    "Gingerbread Man Hot Chocolate": "/game-icons/Gingerbread_Man_Hot_Chocolate.webp",
    "PencilHouse art": "/game-icons/PencilHouse_art.webp",
    "SpecialBeauty BoatWithPirateFlag": "/game-icons/SpecialBeauty_BoatWithPirateFlag.webp",
    "SpecialBeauty China fish": "/game-icons/SpecialBeauty_China_fish.webp",
    "SpecialBeauty KidKite": "/game-icons/SpecialBeauty_KidKite.webp",
    "SpecialBeauty StatueFisherman": "/game-icons/SpecialBeauty_StatueFisherman.webp",
    "SpecialBeauty TreeBroccoli": "/game-icons/SpecialBeauty_TreeBroccoli.webp",
    "SpecialBeauty Valentine flowercart": "/game-icons/SpecialBeauty_Valentine_flowercart.webp",
    "SpecialBeauty chef balloon": "/game-icons/SpecialBeauty_chef_balloon.webp",
    "SpecialBeauty jumping fish": "/game-icons/SpecialBeauty_jumping_fish.webp",
    "SpecialBeauty mobile coffee truck": "/game-icons/SpecialBeauty_mobile_coffee_truck.webp",
    "SpecialBeauty whalefountain fishing": "/game-icons/SpecialBeauty_whalefountain_fishing.webp",
    "Valentine CupidsArrow": "/game-icons/Valentine_CupidsArrow.webp",
    "Valentine lovearch": "/game-icons/Valentine_lovearch.webp",
    "Valentine moon from heaven": "/game-icons/Valentine_moon_from_heaven.webp",
    "beauty candy house": "/game-icons/beauty_candy_house.webp",
    "beauty chalk elephant": "/game-icons/beauty_chalk_elephant.webp",
    "beauty shipUlysses ancient": "/game-icons/beauty_shipUlysses_ancient.webp",
    "beauty tarzan tree": "/game-icons/beauty_tarzan_tree.webp",
    "beauty torchbearer olympiad": "/game-icons/beauty_torchbearer_olympiad.webp",
    "beauty tree ballon": "/game-icons/beauty_tree_ballon.webp",
    "bookTree jungle": "/game-icons/bookTree_jungle.webp",
    "candyTrain surfingers": "/game-icons/candyTrain_surfingers.webp",
    "champion cup": "/game-icons/champion_cup.webp",
    "coconutArmchair bungalow": "/game-icons/coconutArmchair_bungalow.webp",
    "discusThrower ancient": "/game-icons/discusThrower_ancient.webp",
    "fly Valentine Cupid": "/game-icons/fly_Valentine_Cupid.webp",
    "flyingShip treasure": "/game-icons/flyingShip_treasure.webp",
    "fountain tree": "/game-icons/fountain_tree.webp",
    "halloween ghost ship": "/game-icons/halloween_ghost_ship.webp",
    "halloween tree": "/game-icons/halloween_tree.webp",
    "heartTree valentine": "/game-icons/heartTree_valentine.webp",
    "helmetOctopus ancient": "/game-icons/helmetOctopus_ancient.webp",
    "mammoth match3": "/game-icons/mammoth_match3.webp",
    "mechDragon medieval": "/game-icons/mechDragon_medieval.webp",
    "pineapple knife": "/game-icons/pineapple_knife.webp",
    "rainbowFair helix": "/game-icons/rainbowFair_helix.webp",
    "scriptorium medieval": "/game-icons/scriptorium_medieval.webp",
    "sheared Tree": "/game-icons/sheared_Tree.webp",
    "small green tree 04": "/game-icons/small_green_tree_04.webp",
    "stream hedge": "/game-icons/stream_hedge.webp",
    "thanksgiving vegetableBasket": "/game-icons/thanksgiving_vegetableBasket.webp",
    "throneHall medieval": "/game-icons/throneHall_medieval.webp",
    "tree shaping": "/game-icons/tree_shaping.webp",
    "trouveres medieval": "/game-icons/trouveres_medieval.webp",
    "weightlifter runner": "/game-icons/weightlifter_runner.webp",
    "whiterose tree": "/game-icons/whiterose_tree.webp",
    "wishing Well": "/game-icons/wishing_Well.webp",

    "spaceneedle v1": "/game-icons/spaceneedle_v1.webp",
    "5years": "/game-icons/bff_fountain_year_5.webp",
    "apple tree": "/game-icons/apple_tree.webp",
    "asphalt": "/game-icons/asphalt_road.webp",
    "baloons": "/game-icons/balloons.webp",
    "baobab": "/game-icons/baobab.webp",
    "baseball": "/game-icons/baseball_field.webp",
    "Basil Cath": "/game-icons/st_basil_s_cathedral.webp",
    "beach dance floor": "/game-icons/beach_bash_flower_dancefloor.webp",
    "beach fruit mix": "/game-icons/beach_bash_mixed_fruit.webp",
    "beach party bar": "/game-icons/beach_smoothie_bar.webp",
    "Beach volleyball": "/game-icons/beach_volleyball.webp",
    "beach yellow submarine": "/game-icons/beach_bash_yellow_submarine_club.webp",
    "bears family": "/game-icons/bear_family_statue.webp",
    "beauty araguaney": "/game-icons/araguaney.webp",
    "beauty arch balloon": "/game-icons/balloon_arch.webp",
    "beauty atlantis hotel": "/game-icons/hotel_atlantis.webp",
    "beauty atlantis ruins": "/game-icons/ruins_of_atlantis.webp",
    "beauty candy bridge": "/game-icons/Candy_Bridge.png",
    "beauty candy carousel": "/game-icons/candy_carousel.webp",
    "beauty candy tree": "/game-icons/Candy_Tree.png",
    "beauty carousel": "/game-icons/carousel.webp",
    "beauty cave in jungle": "/game-icons/jungle_cave.webp",
    "beauty china town": "/game-icons/chinatown.webp",
    "beauty Coconut bar": "/game-icons/coconut_paradise_juice_bar.webp",
    "beauty confectioner cow": "/game-icons/Confectioner_Cow.png",
    "beauty coral garden": "/game-icons/coral_garden.webp",
    "beauty diamond": "/game-icons/the_biggest_diamond.webp",
    "beauty dinosaur": "/game-icons/land_of_the_dinosaurs_complete.webp",
    "beauty dolphins": "/game-icons/dolphin_topiary.webp",
    "beauty dragon dance": "/game-icons/dragon_dance.webp",
    "beauty elephants": "/game-icons/elephant_drawing.webp",
    "beauty elf house": "/game-icons/elf_house.webp",
    "beauty experiment monument": "/game-icons/experimental_monument.webp",
    "beauty fireworkshop": "/game-icons/easter_shop.webp",
    "beauty fish market": "/game-icons/fishing_wharf_market.webp",
    "beauty Flower gates": "/game-icons/flower_gate.webp",
    "beauty flower vase": "/game-icons/vase_of_flowers.webp",
    "beauty flowerhouse": "/game-icons/aquarist_s_house.webp",
    "beauty flyingship": "/game-icons/Flying_ship.png",
    "beauty Goalkeeper": "/game-icons/fortune_keeper.webp",
    "beauty gondola": "/game-icons/gondola.webp",
    "beauty Gong": "/game-icons/gong.webp",
    "beauty greengrocery": "/game-icons/green_neighborhood_parking.webp",
    "beauty ice castle": "/game-icons/ice_castle.webp",
    "beauty icebreaker": "/game-icons/icebreaker.webp",
    "beauty iceDeer": "/game-icons/ice_sculpture_reindeer.webp",
    "beauty juggler": "/game-icons/juggler.webp",
    "beauty lake house": "/game-icons/lake_house.webp",
    "beauty mammoth": "/game-icons/Mammoth.png",
    "beauty peacock statue": "/game-icons/peacock_statue.webp",
    "beauty pine tree": "/game-icons/Pine_Tree.png",
    "beauty pirate ship bow": "/game-icons/pirate_ship_bow.webp",
    "beauty plane steam": "/game-icons/steam_plane.webp",
    "beauty playground2": "/game-icons/Playground.png",
    "beauty polar bear": "/game-icons/polar_bear_statue.webp",
    "beauty polarStation": "/game-icons/polar_station.webp",
    "beauty poseidon": "/game-icons/poseidon_statue.webp",
    "beauty rhino": "/game-icons/rhino_statue.webp",
    "beauty rhododendron": "/game-icons/rhododendron.webp",
    "beauty sailboat": "/game-icons/beached_boat.webp",
    "beauty saloon": "/game-icons/saloon.webp",
    "beauty seahouse decoration": "/game-icons/florist_house_deco.webp",
    "beauty sequoia": "/game-icons/sequoia.webp",
    "beauty skatingPenguins": "/game-icons/penguin_skating_rink.webp",
    "beauty snowfortress": "/game-icons/snow_fortress.webp",
    "beauty snowslide": "/game-icons/ice_slide.webp",
    "beauty space mars rover": "/game-icons/mars_rover.webp",
    "beauty stonehenge": "/game-icons/stonehenge.webp",
    "beauty submarine": "/game-icons/submarine.webp",
    "beauty thai temple": "/game-icons/thai_temple.webp",
    "beauty treasure chest": "/game-icons/treasure_chest.webp",
    "beauty ufo": "/game-icons/ufo_carousel.webp",
    "beauty waterSlide": "/game-icons/water_slide.webp",
    "beauty wisteria": "/game-icons/wisteria.webp",
    "beauty yeti": "/game-icons/yeti.webp",
    "berryTree knife": "/game-icons/berry_tree.webp",
    "Book Store": "/game-icons/bookstore.webp",
    "cactus": "/game-icons/cactus.webp",
    "camping": "/game-icons/camping_site.webp",
    "candyCastle helix": "/game-icons/candy_castle.webp",
    "caramelApple surfingers": "/game-icons/caramel_apple_decor.webp",
    "carousel elephants": "/game-icons/flying_elephants_carousel.webp",
    "castle": "/game-icons/castle.webp",
    "Chocolate Factory Decor": "/game-icons/chocolate_factory_event_candy_island.webp",
    "Christmas angel": "/game-icons/Ice_Angel.png",
    "Christmas Ball": "/game-icons/christmas_ball.webp",
    "Christmas fence": "/game-icons/christmas_fence.webp",
    "Christmas GingerbreadMan": "/game-icons/Gingerbread_Statue.png",
    "Christmas Ice skating": "/game-icons/christmas_cruise_regatta_squirrel_skating_rink.webp",
    "christmas santa helper": "/game-icons/santa_s_helper.webp",
    "Christmas Santa House": "/game-icons/santa_s_house.webp",
    "Christmas Santas Reinde": "/game-icons/Santas_Reindeer.png",
    "Christmas scene": "/game-icons/christmas_scene.webp",
    "Christmas Snow fortress": "/game-icons/snow_fortress.webp",
    "christmas snowball": "/game-icons/christmas_ball.webp",
    "Christmas Snowman": "/game-icons/snowman_christmas.webp",
    "Christmas Urban tree": "/game-icons/christmas_tree.webp",
    "christmasTree xmas2022": "/game-icons/christmas_tree.webp",
    "colorFountain match3": "/game-icons/bff_fountain_year_3.webp",
    "crater": "/game-icons/crater.webp",
    "crocodile": "/game-icons/crocodile_statue.webp",
    "Cycle Parking": "/game-icons/bicycle_parking.webp",
    "dancing Fountains": "/game-icons/dancing_fountains.webp",
    "discoForever music": "/game-icons/disco_forever.webp",
    "DroneRace plane": "/game-icons/drone_race.webp",
    "Easter fence": "/game-icons/easter_fence.webp",
    "Easter fountain": "/game-icons/easter_fountain.webp",
    "easter Hammock": "/game-icons/easter_hammock.webp",
    "easterhouse tree": "/game-icons/easter_tree.webp",
    "Egypt Papyrus Boat": "/game-icons/papyrus_boat.webp",
    "Egypt Pharaoh Statue": "/game-icons/pharaoh_statue.webp",
    "eifel tower": "/game-icons/Eiffel_Tower.png",
    "Fairy Fountain": "/game-icons/floral_fairy_fountain.webp",
    "fairy water": "/game-icons/water_fairy.webp",
    "flag": "/game-icons/flag.webp",
    "flamingo": "/game-icons/flamingo_statue.webp",
    "floating lanterns": "/game-icons/floating_lanterns.webp",
    "flower fence": "/game-icons/flower_fence.webp",
    "flower swing": "/game-icons/flower_swing.webp",
    "flowerbed 1": "/game-icons/flower_bed_fountain_1.webp",
    "flowerbed 2": "/game-icons/flower_bed_fountain_2.webp",
    "football": "/game-icons/football_champion.webp",
    "fountain 1": "/game-icons/flower_bed_fountain_1.webp",
    "fountain 2": "/game-icons/bff_fountain_year_2.webp",
    "fountain 4": "/game-icons/bff_fountain_year_4.webp",
    "fountain whale": "/game-icons/whale_fountain.webp",
    "Ginger House": "/game-icons/gingerbread_house_2021.webp",
    "Glass Bridge": "/game-icons/glass_bridge.webp",
    "gnomes": "/game-icons/garden_gnomes.webp",
    "golden gate": "/game-icons/golden_gate_bridge.webp",
    "gorilla": "/game-icons/gorilla_statue.webp",
    "Gothic Tower": "/game-icons/gothic_tower.webp",
    "Grape Press": "/game-icons/grape_press.webp",
    "gravelroad": "/game-icons/gravel_road.webp",
    "green": "/game-icons/sun_chairs_green.webp",
    "green 2": "/game-icons/botanical_bonanza_event_2023_2_greenhouse_complex.webp",
    "green tree1": "/game-icons/fir_tree_1.webp",
    "green tree2": "/game-icons/fir_tree_2.webp",
    "green tree3": "/game-icons/leafy_tree_3.webp",
    "ground": "/game-icons/dirt_ground.webp",
    "groundroad": "/game-icons/ground_road.webp",
    "Hall Fame": "/game-icons/hall_of_fame.webp",
    "Happy Aquarium": "/game-icons/happy_aquarium.webp",
    "hay": "/game-icons/fresh_hay.webp",
    "hedge": "/game-icons/hedge.webp",
    "HelixJump TreasureIsland": "/game-icons/treasure_island_playground.webp",
    "Hot Dog Swing": "/game-icons/hot_dog_swings.webp",
    "hotSpring match3": "/game-icons/hot_spring.webp",
    "House Egyptian": "/game-icons/egyptian_house.webp",
    "ice Dragon": "/game-icons/ice_dragon.webp",
    "iceSculptures plank": "/game-icons/ice_sculptures.webp",
    "jakaranda": "/game-icons/jacaranda.webp",
    "Jazz Club": "/game-icons/jazz_club.webp",
    "juice fountain": "/game-icons/beach_bash_orange_juice_fountain.webp",
    "katamaran": "/game-icons/catamaran.webp",
    "koala": "/game-icons/koala_statue.webp",
    "lion": "/game-icons/lion_statue.webp",
    "love bridge": "/game-icons/love_bridge.webp",
    "Mobile Market": "/game-icons/mobile_market.webp",
    "monument tools": "/game-icons/tool_monument.webp",
    "MountainChalet CozyHouse": "/game-icons/cozy_chalet.webp",
    "MountainChalet HuskyHouse": "/game-icons/husky_house.webp",
    "movie Museum": "/game-icons/movie_museum.webp",
    "New Year": "/game-icons/new_years_eve.webp",
    "noodle shop": "/game-icons/noodle_shop.webp",
    "Notre Dame": "/game-icons/notre_dame_de_paris.webp",
    "Organic Shop": "/game-icons/organic_shop.webp",
    "palma 1": "/game-icons/palm_tree_1.webp",
    "palma 2": "/game-icons/three_palm_trees_2.webp",
    "panda": "/game-icons/panda_statue.webp",
    "parking green side": "/game-icons/green_neighborhood_parking.webp",
    "parking green yard": "/game-icons/green_neighborhood_parking.webp",
    "penguin": "/game-icons/penguin_statue.webp",
    "petronas": "/game-icons/petronas.webp",
    "picnic": "/game-icons/picnic_gazebo.webp",
    "pirateShip treasure": "/game-icons/pirate_ship.webp",
    "playground": "/game-icons/playground.webp",
    "pond": "/game-icons/carp_pond.webp",
    "pond mother earth": "/game-icons/mother_nature_pond.webp",
    "pond Swans": "/game-icons/swan_pond.webp",
    "pond with carp": "/game-icons/carp_pond.webp",
    "pool": "/game-icons/swimming_pool.webp",
    "pumpkinrace": "/game-icons/pumpkin_race.webp",
    "pyramide": "/game-icons/pyramid.webp",
    "radar": "/game-icons/ufo_radar.webp",
    "Rainbow Arch": "/game-icons/rainbow_arch.webp",
    "ratGarden jump": "/game-icons/golden_rat_garden.webp",
    "red Lilies Pond": "/game-icons/red_lily_pond.webp",
    "sail Hotel": "/game-icons/sail_hotel.webp",
    "sand": "/game-icons/sand_ground.webp",
    "Santa Sleigh": "/game-icons/santa_s_sleigh.webp",
    "scarecrow": "/game-icons/scarecrow.webp",
    "sea gate": "/game-icons/sea_gates.webp",
    "seal": "/game-icons/fur_seal_statue.webp",
    "Sheep Slide": "/game-icons/sheep_slide.webp",
    "ship": "/game-icons/old_ship.webp",
    "shipAttraction pirate": "/game-icons/pirate_ship.webp",
    "skin city sign cactus sign": "/game-icons/cactus_town_sign.webp",
    "skin city sign christmas sign": "/game-icons/christmas_sign.webp",
    "skin city sign easter sign": "/game-icons/easter_town_sign.webp",
    "skin city sign farm sign": "/game-icons/home_sweet_farm_town_sign.webp",
    "skin city sign flowerbed sign": "/game-icons/flower_town_sign.webp",
    "skin city sign frank halloween": "/game-icons/big_halloween_sign.webp",
    "skin city sign halloween sign": "/game-icons/big_halloween_sign.webp",
    "skin city sign lamp board sign": "/game-icons/lamp_town_sign.webp",
    "skin city sign mechanic sign": "/game-icons/mechanical_town_sign.webp",
    "skin city sign MillSign": "/game-icons/mill_town_sign.webp",
    "skin city sign music sign": "/game-icons/musical_town_sign.webp",
    "skin city sign mystical events": "/game-icons/desert_tales_event_desert_town_sign.webp",
    "skin city sign neon sign": "/game-icons/neon_town_sign.webp",
    "skin city sign palm trees": "/game-icons/palm_tree_1.webp",
    "skin city sign rock sign": "/game-icons/rock_town_sign.webp",
    "skin city sign smoothiebar sign": "/game-icons/smoothie_stand_sign.webp",
    "skin city sign stone sign": "/game-icons/stone_town_sign.webp",
    "skin city sign wild west sign": "/game-icons/wild_west_town_sign.webp",
    "snow": "/game-icons/snow_fight.webp",
    "snowFight plank": "/game-icons/snow_fight.webp",
    "Snowman": "/game-icons/snowman_igloo.webp",
    "spacegarden": "/game-icons/space_garden.webp",
    "SpecialBeauty Aquarium": "/game-icons/city_aquarium.webp",
    "SpecialBeauty Banner": "/game-icons/birthday_banner.webp",
    "SpecialBeauty BeePilot": "/game-icons/bee_pilot.webp",
    "SpecialBeauty BirthdayBanner": "/game-icons/birthday_banner.webp",
    "SpecialBeauty china dragon2017": "/game-icons/chinese_dragon_2017.webp",
    "SpecialBeauty China lightTree": "/game-icons/light_tree.webp",
    "SpecialBeauty CityDay arch of flowers": "/game-icons/arch_of_flowers.webp",
    "SpecialBeauty CityDay boat of flowers": "/game-icons/boat_with_flowers.webp",
    "SpecialBeauty Dovecote": "/game-icons/dovecote.webp",
    "SpecialBeauty Easter EasterBunny": "/game-icons/easter_bunny_s_house.webp",
    "SpecialBeauty Easter EasterTree": "/game-icons/easter_tree.webp",
    "SpecialBeauty Easter FabergeEgg": "/game-icons/easter_faberge_egg.webp",
    "SpecialBeauty Easter FabergeEgg blue": "/game-icons/easter_faberge_egg.webp",
    "SpecialBeauty Easter RabbitHouse": "/game-icons/easter_bunny_s_house.webp",
    "SpecialBeauty Easter SpringGirl": "/game-icons/easter_spring_girl.webp",
    "SpecialBeauty EasterTopiary": "/game-icons/easter_topiary.webp",
    "SpecialBeauty firerooster": "/game-icons/fire_rooster.webp",
    "SpecialBeauty fishermans house": "/game-icons/fisherman_s_house.webp",
    "SpecialBeauty flooded tower": "/game-icons/flooded_tower.webp",
    "SpecialBeauty GiantWatermelon": "/game-icons/giant_watermelon.webp",
    "SpecialBeauty HelicopterTrampoline": "/game-icons/helicopter_trampoline.webp",
    "SpecialBeauty ice cream cafe": "/game-icons/ice_cream_cafe.webp",
    "SpecialBeauty InflatableCastle": "/game-icons/inflatable_castle.webp",
    "SpecialBeauty octopus": "/game-icons/inflatable_octopus.webp",
    "SpecialBeauty PirateTavern": "/game-icons/pirate_tavern.webp",
    "SpecialBeauty PumpkinWheel": "/game-icons/pumpkin_ferris_wheel.webp",
    "SpecialBeauty redBridge": "/game-icons/red_bridge.webp",
    "SpecialBeauty seahorse": "/game-icons/Sea_Horse.png",
    "SpecialBeauty SpiderTree": "/game-icons/spiderweb_tree.webp",
    "SpecialBeauty Sun": "/game-icons/sun_dial.webp",
    "SpecialBeauty topiary egg": "/game-icons/egg_topiary.webp",
    "SpecialBeauty Totem": "/game-icons/farmer_s_totem.webp",
    "SpecialBeauty WaterMill": "/game-icons/watermill.webp",
    "SpecialBeauty WaterTower": "/game-icons/Water_Tower.png",
    "SpecialBeauty wealth bowl": "/game-icons/bowl_of_wealth.webp",
    "sunflower": "/game-icons/sunflowers.webp",
    "swan": "/game-icons/swan_statue.webp",
    "sydney opera": "/game-icons/sydney_opera_house.webp",
    "teahouse": "/game-icons/tea_house.webp",
    "tennis": "/game-icons/tennis_court.webp",
    "thanksgiving CarrotTree": "/game-icons/carrot_tree.webp",
    "tiger": "/game-icons/crouching_tiger_statue.webp",
    "Tiki Bar": "/game-icons/tiki_bar.webp",
    "topiary castle": "/game-icons/castle_topiary.webp",
    "Tower of Pisa": "/game-icons/leaning_tower_of_pisa.webp",
    "Tree Market": "/game-icons/holiday_tree_market.webp",
    "Trio": "/game-icons/magnificent_trio.webp",
    "trojanHorse ancient": "/game-icons/trojan_horse.webp",
    "turbosledge santa": "/game-icons/santa_s_turbo_sleigh.webp",
    "upsideDownHouse bungalow": "/game-icons/upside_down_house.webp",
    "Valentine Pond with swans": "/game-icons/swan_pond.webp",
    "Valentine Teddy bear": "/game-icons/teddy_bear.webp",
    "Valentine Teddy bear2": "/game-icons/teddy_bear.webp",
    "vegetables": "/game-icons/vegetable_display.webp",
    "village jungle": "/game-icons/jungle_village.webp",
    "water": "/game-icons/water_fairy.webp",
    "water flowers 1": "/game-icons/flower_bed_fountain_1.webp",
    "water flowers 2": "/game-icons/flower_bed_fountain_2.webp",
    "wateringCan easter": "/game-icons/watering_can_flowerbed.webp",
    "weeping willow": "/game-icons/weeping_willow.webp",
    "well": "/game-icons/well.webp",
    "wildpark": "/game-icons/wild_park.webp",
    "windmill": "/game-icons/misty_hills_event_halloween_windmill.webp",
    "yacht": "/game-icons/yacht.webp",
    "yellow roses": "/game-icons/yellow_roses.webp",
    "zebra": "/game-icons/zebra_statue.webp",
    "zoo decor": "/game-icons/petting_zoo.webp",
    "Small Waterfall": "/game-icons/waterfall.webp",
    "SpecialBeauty China maneki": "/game-icons/maneki.webp",
    "Valentine Gazebo lovers": "/game-icons/gazebo.webp",
    "airboat plank": "/game-icons/airboat.webp",
    "beauty acacia giraffe": "/game-icons/acacia.webp",
    "beauty divers boat": "/game-icons/diver.webp",
    "beauty swing giraffe": "/game-icons/swings.webp",
    "curling runner": "/game-icons/curling.webp",
    "flowerbed gerbera": "/game-icons/gerberas.webp",
    "flowerbed irises": "/game-icons/irises.webp",
    "flowerbed poppies": "/game-icons/poppies.webp",
    "ghostly Carriage": "/game-icons/carriage.webp",
    "halloween gargoyle": "/game-icons/gargoyle.webp",
    "halloween sarcophagus": "/game-icons/sarcophagus.webp",
    "lowriders rescue": "/game-icons/lowriders.webp",
    "minotaur ancient": "/game-icons/minotaur.webp",
    "pinball helix": "/game-icons/pinball.webp",
    "roman chariot": "/game-icons/chariot.webp",
    "sphinx v1": "/game-icons/sphinx.webp",
    "tree adenium": "/game-icons/adenium.webp",
    "zoo restaurant": "/game-icons/restaurant.webp",
    "flower house": "/game-icons/florist_house.webp",
    "Apple Garden": "/game-icons/apple_orchard.webp",
    "Arabic Tent": "/game-icons/colorful_tent.webp",
    "Atlantis fence": "/game-icons/decorative_fence.webp",
    "Bobsleigh Race": "/game-icons/sack_race.webp",
    "Bungalow hammock": "/game-icons/beach_bungalow.webp",
    "Cafe Tube": "/game-icons/cafe_0.webp",
    "Cafe Vineyard": "/game-icons/vineyard_terrace.webp",
    "Cafe Waterfall": "/game-icons/waterfall_terrace.webp",
    "Carousel Octopus": "/game-icons/gramophone_carousel.webp",
    "Castle Trampoline": "/game-icons/bouncy_castle.webp",
    "Chinese Banner": "/game-icons/chinese_house.webp",
    "Chinese Dog": "/game-icons/inflatable_dog.webp",
    "Christmas Banner": "/game-icons/christmas_on_wheels.webp",
    "Christmas lantern": "/game-icons/phantom_lantern.webp",
    "Christmas train": "/game-icons/kids_train_ride.webp",
    "Circus Camping": "/game-icons/summer_camping.webp",
    "Color Egg": "/game-icons/faberge_egg.webp",
    "Connect Station": "/game-icons/canyon_station.webp",
    "Cover Gift": "/game-icons/gift_shop.webp",
    "Cow Artist": "/game-icons/inflatable_cow.webp",
    "Cowboy Tower": "/game-icons/astrologists_tower.webp",
    "Crab Cook": "/game-icons/crab_chef.webp",
    "Crane Fountain": "/game-icons/cascading_fountain.webp",
    "Dino Safe": "/game-icons/dino_park.webp",
    "Easter Stump": "/game-icons/easter_fun.webp",
    "Egypt Pyramid": "/game-icons/pyramid_of_cheops.webp",
    "Fashion Boutique": "/game-icons/fashion_gallery.webp",
    "Flower Statue": "/game-icons/affection_statue.webp",
    "Flower Store": "/game-icons/beverage_store.webp",
    "Ghost Garden": "/game-icons/ghost_huntress.webp",
    "Giant Snowman": "/game-icons/giant_aquarium.webp",
    "Glamping Camp": "/game-icons/floating_camp.webp",
    "Glamping House": "/game-icons/bunny_house.webp",
    "Gold Diggers": "/game-icons/gold_mine.webp",
    "Greenhouse Predator": "/game-icons/carnivorous_greenhouse.webp",
    "Halloween Park": "/game-icons/adventure_park.webp",
    "Horn Harvest": "/game-icons/goddess_of_harvest.webp",
    "Hot Fountain": "/game-icons/hot_springs_2021.webp",
    "Installation Insomnia": "/game-icons/natural_wonder_installation.webp",
    "Instrument Workshop": "/game-icons/santa_s_workshop.webp",
    "Kids Railway": "/game-icons/kids_playground.webp",
    "Love Lock": "/game-icons/bear_in_love.webp",
    "Marsh treasure": "/game-icons/rabbit_treasure.webp",
    "Mechanic Car": "/game-icons/bumper_car_ride.webp",
    "Mega Cake": "/game-icons/the_biggest_cake.webp",
    "Music Carousele": "/game-icons/music_district.webp",
    "NewCinema gatsby": "/game-icons/new_heights.webp",
    "Newyear Globe": "/game-icons/plasma_globe.webp",
    "Palace of the sky": "/game-icons/conqueror_of_the_seas.webp",
    "Palette Sculpture": "/game-icons/palette_flowerbed.webp",
    "Paris Street": "/game-icons/sweet_tooth_street.webp",
    "Pig Oscar": "/game-icons/inflatable_pig.webp",
    "Pirate Fort": "/game-icons/pirate_corner.webp",
    "Plank Shop": "/game-icons/ice_cream_shop.webp",
    "Plank Werewolf": "/game-icons/werewolf_show.webp",
    "Pumpkin House": "/game-icons/cart_with_pumpkin.webp",
    "Rialto Bridge": "/game-icons/bridge_for_two.webp",
    "Santa Reception": "/game-icons/photo_with_santa.webp",
    "SeaFence fence": "/game-icons/deep_sea_explorer.webp",
    "SheepElf runner": "/game-icons/inflatable_sheep.webp",
    "Ship Tower": "/game-icons/haunted_ship.webp",
    "Ski Shop": "/game-icons/jet_ski.webp",
    "Space Rocket": "/game-icons/space_needle.webp",
    "SpecialBeauty StatueOfTheCook": "/game-icons/riches_of_the_seas_statue.webp",
    "Summer Cafe": "/game-icons/summer_caf.webp",
    "Sweet Tree": "/game-icons/balloon_tree.webp",
    "Town Fair": "/game-icons/aloha_town_sign.webp",
    "Trucks Decotor": "/game-icons/monster_trucks.webp",
    "Valentine Bunny": "/game-icons/bunny_village_8.webp",
    "Valentine Flowerbed": "/game-icons/sheep_flowerbed.webp",
    "Valentine Statue of cupid": "/game-icons/statue_of_liberty.webp",
    "Valentine Swing lovers": "/game-icons/beach_swing.webp",
    "Valentine Topiary": "/game-icons/bird_topiary.webp",
    "Valentine lovers bench": "/game-icons/friendship_bench.webp",
    "Valentine lovers cart": "/game-icons/veggie_cart.webp",
    "Valentine serenade": "/game-icons/endless_serenade.webp",
    "Wagon Mountain": "/game-icons/mountain_of_presents.webp",
    "Witch Pot": "/game-icons/witch_parking.webp",
    "ancient bridge": "/game-icons/ancient_calendar.webp",
    "aquarium v1": "/game-icons/atlantean_aquarium.webp",
    "aquariumHouse fishing": "/game-icons/fishing_boat.webp",
    "arabic jin lamp": "/game-icons/magic_lamp.webp",
    "arabic oasis": "/game-icons/oasis.webp",
    "ballShooting helix": "/game-icons/stone_ball.webp",
    "bamboo runner": "/game-icons/bamboo_grove.webp",
    "bar fin": "/game-icons/snack_bar.webp",
    "basketball 1x2": "/game-icons/basketball_court.webp",
    "beauty SuperheroStand": "/game-icons/fireworks_stand.webp",
    "beauty atlantis boulevard": "/game-icons/long_boulevard.webp",
    "beauty balloon dancer": "/game-icons/air_dancer.webp",
    "beauty chalk zebra": "/game-icons/zebra_drawing.webp",
    "beauty dragon boat": "/game-icons/boat_deco.webp",
    "beauty experiment projector": "/game-icons/3d_projector.webp",
    "beauty fish ballon": "/game-icons/inflatable_fish.webp",
    "beauty goldberg machine": "/game-icons/claw_machine.webp",
    "beauty iceberg penguin": "/game-icons/inflatable_penguin.webp",
    "beauty simulator plane": "/game-icons/flight_simulator.webp",
    "beauty water monster": "/game-icons/water_ground.webp",
    "beauty winter cannon": "/game-icons/fruit_cannon.webp",
    "big Picnic": "/game-icons/big_ben.webp",
    "bronze bull": "/game-icons/angry_bull.webp",
    "buek 1": "/game-icons/spring_1.webp",
    "candy fence": "/game-icons/candy_express.webp",
    "candy gate": "/game-icons/gingerbread_gate.webp",
    "candy rainbow": "/game-icons/rainbow_factory.webp",
    "captainStatue pirate": "/game-icons/legendary_captain.webp",
    "chamber halloween": "/game-icons/chamber_of_horrors.webp",
    "chess arabic": "/game-icons/chess_match.webp",
    "danceMachine helix": "/game-icons/dance_off.webp",
    "easter factory": "/game-icons/paint_block_factory.webp",
    "easter pond": "/game-icons/mystery_pond.webp",
    "eastern Bazar": "/game-icons/eastern_bazaar.webp",
    "fly Bee": "/game-icons/fly_seasoned_friends.webp",
    "fly Dragon": "/game-icons/inflatable_dragon.webp",
    "fly Panda": "/game-icons/inflatable_panda.webp",
    "fruitFootball knife": "/game-icons/fruit_master.webp",
    "gallery art": "/game-icons/art_hub.webp",
    "gardens arabic": "/game-icons/hanging_gardens.webp",
    "green elephant": "/game-icons/inflatable_elephant.webp",
    "green turtle": "/game-icons/inflatable_turtle.webp",
    "green5 2": "/game-icons/snow_fortress_2.webp",
    "halloween cat": "/game-icons/black_cat.webp",
    "halloween museum": "/game-icons/atlantean_museum.webp",
    "hockeyField runner": "/game-icons/soccer_field.webp",
    "ice Lake": "/game-icons/frozen_lake.webp",
    "iceArch arctic": "/game-icons/triumphal_arch.webp",
    "jetpack plane": "/game-icons/experimental_plane.webp",
    "kitchen plank": "/game-icons/field_kitchen.webp",
    "lakehouse home": "/game-icons/cozy_home_sign.webp",
    "lifeguard hut": "/game-icons/warlock_s_hut.webp",
    "lion slides": "/game-icons/lion_drawing.webp",
    "love flowers": "/game-icons/cart_with_flowers.webp",
    "movie Monument": "/game-icons/movie_magic.webp",
    "oil Derrick": "/game-icons/oil_well.webp",
    "palm Hotel": "/game-icons/date_palm.webp",
    "parking common": "/game-icons/city_parking_lot.webp",
    "phone box": "/game-icons/phone_booth.webp",
    "plane Aircraft Reward": "/game-icons/amphibious_aircraft.webp",
    "polarman arctic": "/game-icons/arctic_glacier.webp",
    "reef hedge": "/game-icons/coral_reef.webp",
    "ringGame surfingers": "/game-icons/shell_game.webp",
    "rockCat music": "/game-icons/kitty_rock.webp",
    "rodeoHelic runner": "/game-icons/pickup_rodeo.webp",
    "rose bush": "/game-icons/the_rose.webp",
    "rugby stadium": "/game-icons/rugby_field.webp",
    "seasonCinecamera cinema": "/game-icons/holiday_season.webp",
    "shooting rescue": "/game-icons/star_shooting_range.webp",
    "stairs match3": "/game-icons/endless_stairs.webp",
    "statue chemist": "/game-icons/the_first_chemist.webp",
    "statue geneticist": "/game-icons/the_first_geneticist.webp",
    "statue policeman": "/game-icons/the_first_policeman.webp",
    "statue thinker": "/game-icons/the_first_thinker.webp",
    "statue tourist": "/game-icons/the_first_tourist.webp",
    "statue writer": "/game-icons/the_first_writer.webp",
    "theaterOdeon ancient": "/game-icons/4d_theater.webp",
    "tractor and hay": "/game-icons/hay_making.webp",
    "tree with stairs": "/game-icons/tree_with_pumpkins.webp",
    "ufo Clue": "/game-icons/ufo_trace.webp",
    "white fence": "/game-icons/white_water_lily.webp",
    "yacht fin": "/game-icons/pleasure_yacht.webp",
    "young gardeners": "/game-icons/young_cowboys_playground.webp",
    "zoo caffe": "/game-icons/zoo_road_road.webp",
    "zoo contact": "/game-icons/first_contact.webp",
    "AquariumAtlantic ancient": "/game-icons/greek_aquarium.webp",
    "Chinese fence": "/game-icons/chinese_lion.webp",
    "Christmas Cafe": "/game-icons/pirate_cafe.webp",
    "Christmas Carousel": "/game-icons/christmas_stocking.webp",
    "ChristmasTrain Bridge": "/game-icons/rope_bridge.webp",
    "Easter Vineyard": "/game-icons/easter_maze.webp",
    "House Garden": "/game-icons/cursed_house.webp",
    "Jurassic Park": "/game-icons/botanical_amusement_park.webp",
    "Lira Fountain": "/game-icons/chocolate_fountain.webp",
    "Love Tunnel": "/game-icons/pilot_in_love.webp",
    "Music Scene": "/game-icons/music_shop.webp",
    "Pin Sculpture": "/game-icons/sculpture_s_workshop.webp",
    "Pumpkin Metro": "/game-icons/pumpkin_man.webp",
    "Sale Square": "/game-icons/grand_harvest_square.webp",
    "Ship Fight": "/game-icons/odysseus_ship.webp",
    "Surfingers Trampoline": "/game-icons/jelly_trampoline.webp",
    "Train Conductor": "/game-icons/train_slide.webp",
    "Tree sakura": "/game-icons/basket_tree.webp",
    "Trucks PirateBistro": "/game-icons/pirate_camp.webp",
    "baloon castle": "/game-icons/ice_castle_slide.webp",
    "beauty FootballDog": "/game-icons/yellow_dog.webp",
    "beauty MovieFountain": "/game-icons/movie_set.webp",
    "beauty ancient town": "/game-icons/cowboy_town.webp",
    "beauty easter stump": "/game-icons/mushroom_stump.webp",
    "beauty floral sheeps": "/game-icons/floral_boutique.webp",
    "beauty sea researchers": "/game-icons/sea_herald.webp",
    "beauty swing palm": "/game-icons/sky_swing.webp",
    "bullStatue runner": "/game-icons/golden_bull.webp",
    "dark Forest With Train Sign": "/game-icons/the_case_of_the_dark_hound_event_supernatural_town_sign.webp",
    "filmmaking treasure": "/game-icons/treasure_keeper.webp",
    "flower hedge": "/game-icons/car_flower_bed.webp",
    "fruitPark knife": "/game-icons/fruit_village.webp",
    "giantVegetables rescue": "/game-icons/giant_puzzle.webp",
    "globalFlight plane": "/game-icons/inflatable_plane.webp",
    "green bunny": "/game-icons/talented_bunny_statue.webp",
    "green peacock": "/game-icons/peacock_topiary.webp",
    "halloween witch": "/game-icons/witch_shop.webp",
    "ice dino": "/game-icons/ice_angel.webp",
    "installation art": "/game-icons/art_show.webp",
    "lookout point": "/game-icons/lookout_tower.webp",
    "love Tower": "/game-icons/astronomical_tower.webp",
    "oasis egypt": "/game-icons/oasis_hotel.webp",
    "railway station": "/game-icons/comms_station.webp",
    "retro avto": "/game-icons/retro_movie_theater.webp",
    "scarab egypt": "/game-icons/scarab_statue.webp",
    "sculptor ancient": "/game-icons/ancient_city_site.webp",
    "statue artist": "/game-icons/bff_statue.webp",
    "statue boat gold": "/game-icons/pleasure_boat.webp",
    "topiary competition": "/game-icons/elephant_topiary.webp",
    "winterYurt xmas2022": "/game-icons/winter_fun.webp",
    "workshop Crash": "/game-icons/scribe_s_workshop.webp",
    "zoo cinema": "/game-icons/zoo_rocky_road.webp",
    "zoo shop": "/game-icons/papyrus_shop.webp",
    "Christmas Chorus": "/game-icons/christmas_town_sign.webp",
    "Decor FlowerShop": "/game-icons/flower_arch.webp",
    "Decor TreeHouse": "/game-icons/flying_house.webp",
    "Easter bunnies": "/game-icons/easter_railway.webp",
    "Horse Carousel": "/game-icons/kids_carousel.webp",
    "IceExhibition runner": "/game-icons/ice_gate.webp",
    "Valentine topiary hearts": "/game-icons/topiary_show.webp",
    "beauty ancient drums": "/game-icons/ancient_throne.webp",
    "beauty artist quarter": "/game-icons/street_artist.webp",
    "beauty astronomer tower": "/game-icons/eiffel_tower.webp",
    "beauty chalk lion": "/game-icons/lion_trampoline.webp",
    "beauty ghost ship": "/game-icons/phantom_ship.webp",
    "beauty large sundial": "/game-icons/large_park.webp",
    "cafe rescue": "/game-icons/robot_cafe.webp",
    "flowering tree": "/game-icons/cedar_tree.webp",
    "fountain swan": "/game-icons/classic_fountain.webp",
    "granite fence": "/game-icons/gingerbread_fence.webp",
    "halloween castle": "/game-icons/mysterious_castle.webp",
    "halloween scarecrow": "/game-icons/pumpkin_scarecrow.webp",
    "love Wings": "/game-icons/garden_of_love.webp",
    "museum atlantis": "/game-icons/ice_museum.webp",
    "pirateStatue treasure": "/game-icons/pirate_playground.webp",
    "seaStation dive": "/game-icons/marine_station.webp",
    "shark slide": "/game-icons/shark_jaw_trampoline.webp",
    "statue fireman": "/game-icons/ancient_statue.webp",
    "zoo eatery": "/game-icons/zoo_sand_road.webp",
  },
  "profileByLabel": {
    "Badge 1": "/game-icons/Badge_1.png",
    "Badge 10": "/game-icons/Badge_10.png",
    "Badge 11": "/game-icons/Badge_11.png",
    "Badge 12": "/game-icons/Badge_12.png",
    "Badge 13": "/game-icons/Badge_13.png",
    "Badge 14": "/game-icons/Badge_14.png",
    "Badge 15": "/game-icons/Badge_15.png",
    "Badge 16": "/game-icons/Badge_16.png",
    "Badge 2": "/game-icons/Badge_2.png",
    "Badge 3": "/game-icons/Badge_3.png",
    "Badge 4": "/game-icons/Badge_4.png",
    "Badge 5": "/game-icons/Badge_5.png",
    "Badge 6": "/game-icons/Badge_6.png",
    "Badge 7": "/game-icons/Badge_7.png",
    "Badge 8": "/game-icons/Badge_8.png",
    "Badge 9": "/game-icons/Badge_9.png",
    "Frame 1": "/game-icons/Frame_1.png",
    "Frame 10": "/game-icons/Frame_10.png",
    "Frame 11": "/game-icons/Frame_11.png",
    "Frame 12": "/game-icons/Frame_12.png",
    "Frame 13": "/game-icons/Frame_13.png",
    "Frame 14": "/game-icons/Frame_14.png",
    "Frame 15": "/game-icons/Frame_15.png",
    "Frame 2": "/game-icons/Frame_2.png",
    "Frame 3": "/game-icons/Frame_3.png",
    "Frame 4": "/game-icons/Frame_4.png",
    "Frame 5": "/game-icons/Frame_5.png",
    "Frame 6": "/game-icons/Frame_6.png",
    "Frame 7": "/game-icons/Frame_7.png",
    "Frame 8": "/game-icons/Frame_8.png",
    "Frame 9": "/game-icons/Frame_9.png",
    "Title 1": "/game-icons/Title_1.png",
    "Title 10": "/game-icons/Title_10.png",
    "Title 11": "/game-icons/Title_11.png",
    "Title 12": "/game-icons/Title_12.png",
    "Title 13": "/game-icons/Title_13.png",
    "Title 14": "/game-icons/Title_14.png",
    "Title 15": "/game-icons/Title_15.png",
    "Title 16": "/game-icons/Title_16.png",
    "Title 17": "/game-icons/Title_17.png",
    "Title 18": "/game-icons/Title_18.png",
    "Title 19": "/game-icons/Title_19.png",
    "Title 2": "/game-icons/Title_2.png",
    "Title 20": "/game-icons/Title_20.png",
    "Title 3": "/game-icons/Title_3.png",
    "Title 4": "/game-icons/Title_4.png",
    "Title 5": "/game-icons/Title_5.png",
    "Title 6": "/game-icons/Title_6.png",
    "Title 7": "/game-icons/Title_7.png",
    "Title 8": "/game-icons/Title_8.png",
    "Title 9": "/game-icons/Title_9.png",
    "Festival": "/game-icons/Style_Festival.png"
  },
  "gemById": {
    "Gem 1": "/game-icons/Gem1.webp",
    "Gem 2": "/game-icons/Gem2.webp",
    "Gem 3": "/game-icons/Gem3.webp"
  },
  "zooByPaddock": {
"paddock_WhiteOwl": "/zoo/snowy_owl.webp",
    "paddock_anteater": "/zoo/anteater.webp",
    "paddock_arcticfox": "/zoo/arctic_fox.webp",
    "paddock_bear": "/zoo/bear.webp",
    "paddock_beaver": "/zoo/beaver.webp",
    "paddock_boar": "/zoo/wild_boar.webp",
    "paddock_camel": "/zoo/camel.webp",
    "paddock_crane": "/zoo/black_crowned_crane.webp",
    "paddock_crocodile": "/zoo/crocodile.webp",
    "paddock_deer": "/zoo/reindeer.webp",
    "paddock_eagle": "/zoo/bald_eagle.webp",
    "paddock_elephant": "/zoo/elephant.webp",
    "paddock_fennec": "/zoo/fennec_fox.webp",
    "paddock_flamingo": "/zoo/flamingo.webp",
    "paddock_gazelle": "/zoo/gazelle.webp",
    "paddock_girrafe": "/zoo/giraffe.webp",
    "paddock_gorilla": "/zoo/gorilla.webp",
    "paddock_hippo": "/zoo/hippopotamus.webp",
    "paddock_kangaroo": "/zoo/kangaroo.webp",
    "paddock_koala": "/zoo/koala.webp",
    "paddock_lion": "/zoo/lion.webp",
    "paddock_llama": "/zoo/llama.webp",
    "paddock_lynx": "/zoo/lynx.webp",
    "paddock_monkey": "/zoo/chimpanzee.webp",
    "paddock_muskOx": "/zoo/muskox.webp",
    "paddock_ostrich": "/zoo/ostrich.webp",
    "paddock_panda": "/zoo/panda.webp",
    "paddock_panther": "/zoo/black_panther.webp",
    "paddock_parrot": "/zoo/macaw.webp",
    "paddock_peacock": "/zoo/peacock.webp",
    "paddock_pelican": "/zoo/pelican.webp",
    "paddock_penguin": "/zoo/penguin.webp",
    "paddock_platypus": "/zoo/platypus.webp",
    "paddock_polar_bear": "/zoo/polar_bear.webp",
    "paddock_polarwolf": "/zoo/arctic_wolf.webp",
    "paddock_porcupine": "/zoo/porcupine.webp",
    "paddock_raccoon": "/zoo/raccoon.webp",
    "paddock_redPanda": "/zoo/red_panda.webp",
    "paddock_rhino": "/zoo/rhinoceros.webp",
    "paddock_seal": "/zoo/seal.webp",
    "paddock_skunk": "/zoo/skunk.webp",
    "paddock_snow_monkey": "/zoo/snow_monkey.webp",
    "paddock_tapir": "/zoo/tapir.webp",
    "paddock_tiger": "/zoo/tiger.webp",
    "paddock_toucan": "/zoo/toucan.webp",
    "paddock_walrus": "/zoo/walrus.webp",
    "paddock_zebra": "/zoo/zebra.webp",
  },
  "upgradesById": {
    "1": "/upgrades/train_1.webp",
    "2": "/upgrades/train_2.webp",
    "3": "/upgrades/train_3.webp",
    "bagfactory": "/upgrades/bagfactory.webp",
    "bakery": "/upgrades/bakery.webp",
    "bouquetfactory": "/upgrades/bouquetfactory.webp",
    "cakefactory": "/upgrades/cakefactory.webp",
    "candyfactory": "/upgrades/candyfactory.webp",
    "chipsfactory": "/upgrades/chipsfactory.webp",
    "chocolatefactory": "/upgrades/chocolatefactory.webp",
    "clothingfactory": "/upgrades/clothingfactory.webp",
    "coffeefactory": "/upgrades/coffeefactory.webp",
    "cottonfactory": "/upgrades/cottonfactory.webp",
    "dollfactory": "/upgrades/dollfactory.webp",
    "drinksfactory": "/upgrades/drinksfactory.webp",
    "factory_music_instruments": "/upgrades/factory_music_instruments.webp",
    "fastfoodfactory": "/upgrades/fastfoodfactory.webp",
    "featherfactory": "/upgrades/featherfactory.webp",
    "frenchrestaurant": "/upgrades/frenchrestaurant.webp",
    "furniturefactory": "/upgrades/furniturefactory.webp",
    "gardeningfactory": "/upgrades/gardeningfactory.webp",
    "holidayfactory": "/upgrades/holidayfactory.webp",
    "hotdogfactory": "/upgrades/hotdogfactory.webp",
    "housewaresfactory": "/upgrades/housewaresfactory.webp",
    "i1": "/upgrades/i1.webp",
    "i2": "/upgrades/i2.webp",
    "i3": "/upgrades/i3.webp",
    "i4": "/upgrades/i4.webp",
    "i5": "/upgrades/i5.webp",
    "icecreamfactory": "/upgrades/icecreamfactory.webp",
    "italyfoodfactory": "/upgrades/italyfoodfactory.webp",
    "jamfactory": "/upgrades/jamfactory.webp",
    "jewelryfactory": "/upgrades/jewelryfactory.webp",
    "kitchenwarefactory": "/upgrades/kitchenwarefactory.webp",
    "mexfoodfactory": "/upgrades/mexfoodfactory.webp",
    "milkfactory": "/upgrades/milkfactory.webp",
    "mill": "/upgrades/mill.webp",
    "paperfactory": "/upgrades/paperfactory.webp",
    "petfactory": "/upgrades/petfactory.webp",
    "roasterfactory": "/upgrades/roasterfactory.webp",
    "scentfactory": "/upgrades/scentfactory.webp",
    "semifinishedfactory": "/upgrades/semifinishedfactory.webp",
    "shoefactory": "/upgrades/shoefactory.webp",
    "spongefactory": "/upgrades/spongefactory.webp",
    "stationeryfactory": "/upgrades/stationeryfactory.webp",
    "sugarfactory": "/upgrades/sugarfactory.webp",
    "sushifactory": "/upgrades/sushifactory.webp",
    "tea_factory": "/upgrades/tea_factory.webp",
    "vegancafe": "/upgrades/vegancafe.webp",
    "wheelfactory": "/upgrades/wheelfactory.webp",
  },
  "upgradesByLabel": {
    "Bag": "/upgrades/bagfactory.webp",
    "Bakery": "/upgrades/bakery.webp",
    "Bouquet": "/upgrades/bouquetfactory.webp",
    "Cake": "/upgrades/cakefactory.webp",
    "Candy": "/upgrades/candyfactory.webp",
    "Chips": "/upgrades/chipsfactory.webp",
    "Chocolate": "/upgrades/chocolatefactory.webp",
    "Clothing": "/upgrades/clothingfactory.webp",
    "Coffee": "/upgrades/coffeefactory.webp",
    "Cotton": "/upgrades/cottonfactory.webp",
    "Doll": "/upgrades/dollfactory.webp",
    "Drinks": "/upgrades/drinksfactory.webp",
    "Music Instruments": "/upgrades/factory_music_instruments.webp",
    "Fastfood": "/upgrades/fastfoodfactory.webp",
    "Feather": "/upgrades/featherfactory.webp",
    "Frenchrestaurant": "/upgrades/frenchrestaurant.webp",
    "Furniture": "/upgrades/furniturefactory.webp",
    "Gardening": "/upgrades/gardeningfactory.webp",
    "Holiday": "/upgrades/holidayfactory.webp",
    "Hotdog": "/upgrades/hotdogfactory.webp",
    "Housewares": "/upgrades/housewaresfactory.webp",
    "Icecream": "/upgrades/icecreamfactory.webp",
    "Italyfood": "/upgrades/italyfoodfactory.webp",
    "Jam": "/upgrades/jamfactory.webp",
    "Jewelry": "/upgrades/jewelryfactory.webp",
    "Kitchenware": "/upgrades/kitchenwarefactory.webp",
    "Mexfood": "/upgrades/mexfoodfactory.webp",
    "Milk": "/upgrades/milkfactory.webp",
    "Mill": "/upgrades/mill.webp",
    "Paper": "/upgrades/paperfactory.webp",
    "Pet": "/upgrades/petfactory.webp",
    "Roaster": "/upgrades/roasterfactory.webp",
    "Scent": "/upgrades/scentfactory.webp",
    "Semifinished": "/upgrades/semifinishedfactory.webp",
    "Shoe": "/upgrades/shoefactory.webp",
    "Sponge": "/upgrades/spongefactory.webp",
    "Stationery": "/upgrades/stationeryfactory.webp",
    "Sugar": "/upgrades/sugarfactory.webp",
    "Sushi": "/upgrades/sushifactory.webp",
    "Tea": "/upgrades/tea_factory.webp",
    "Vegancafe": "/upgrades/vegancafe.webp",
    "Wheel": "/upgrades/wheelfactory.webp",
    "Train 1": "/upgrades/train_1.webp",
    "Train 2": "/upgrades/train_2.webp",
    "Train 3": "/upgrades/train_3.webp",
    "Island 1": "/upgrades/i1.webp",
    "Island 2": "/upgrades/i2.webp",
    "Island 3": "/upgrades/i3.webp",
    "Island 4": "/upgrades/i4.webp",
    "Island 5": "/upgrades/i5.webp",
  },
  "stickerById": {
    "sp1": "/game-icons/Sticker_001.png",
    "sp4": "/game-icons/Sticker_002.png",
    "sp5": "/game-icons/Sticker_003.png",
    "sp6": "/game-icons/Sticker_004.png",
    "sp7": "/game-icons/Sticker_005.png",
    "sp8": "/game-icons/Sticker_006.png",
    "sp9": "/game-icons/Sticker_007.png",
    "sp11": "/game-icons/Sticker_008.png",
    "sp12": "/game-icons/Sticker_009.png",
    "sp10": "/game-icons/Sticker_010.png",
    "sp15": "/game-icons/Sticker_011.png",
    "sp14": "/game-icons/Sticker_012.png",
    "sp13": "/game-icons/Sticker_013.png",
    "sp17": "/game-icons/Sticker_014.png",
    "sp16": "/game-icons/Sticker_015.png",
    "sp18": "/game-icons/Sticker_016.png",
    "v1": "/game-icons/Sticker_017.png",
    "v2": "/game-icons/Sticker_018.png",
    "v3": "/game-icons/Sticker_019.png",
    "sp21": "/game-icons/Sticker_020.png",
    "sp20": "/game-icons/Sticker_021.png",
    "sp19": "/game-icons/Sticker_022.png",
    "sp22": "/game-icons/Sticker_023.png",
    "sp24": "/game-icons/Sticker_024.png",
    "sp23": "/game-icons/Sticker_025.png",
    "st1": "/game-icons/Sticker_026.png",
    "st3": "/game-icons/Sticker_027.png",
    "st2": "/game-icons/Sticker_028.png",
    "sp25": "/game-icons/Sticker_029.png",
    "sp27": "/game-icons/Sticker_030.png",
    "sp26": "/game-icons/Sticker_031.png",
    "st7": "/game-icons/Sticker_032.png",
    "st11": "/game-icons/Sticker_033.png",
    "st15": "/game-icons/Sticker_034.png",
    "st17": "/game-icons/Sticker_035.png",
    "st23": "/game-icons/Sticker_036.png",
    "st22": "/game-icons/Sticker_037.png",
    "st26": "/game-icons/Sticker_038.png",
    "st25": "/game-icons/Sticker_039.png",
    "st24": "/game-icons/Sticker_040.png",
    "st28": "/game-icons/Sticker_041.png",
    "st27": "/game-icons/Sticker_042.png",
    "st30": "/game-icons/Sticker_043.png",
    "st29": "/game-icons/Sticker_044.png",
    "st32": "/game-icons/Sticker_045.png",
    "st31": "/game-icons/Sticker_046.png",
    "st34": "/game-icons/Sticker_047.png",
    "st35": "/game-icons/Sticker_048.png",
    "st36": "/game-icons/Sticker_049.png",
    "st38": "/game-icons/Sticker_050.png",
    "st37": "/game-icons/Sticker_051.png",
    "st39": "/game-icons/Sticker_052.png"
  }
} as const;

export function iconForStat(key: string): string | null {
  return (GAME_ICON_MAP.stats as Record<string, string>)[key] ?? null;
}

export function iconForItemLabel(label: string): string | null {
  return (GAME_ICON_MAP.itemsByLabel as Record<string, string>)[label] ?? null;
}

export function iconForBarn(id: string): string | null {
  return (GAME_ICON_MAP.barn as Record<string, string>)[id] ?? null;
}

export function iconForGroup(groupId: string): string | null {
  return (GAME_ICON_MAP.groups as Record<string, string>)[groupId] ?? null;
}

export function iconForSkin(groupId: string, label: string): string | null {
  const g = (GAME_ICON_MAP.skinsByGroupLabel as Record<string, Record<string, string>>)[groupId];
  return g?.[label] ?? null;
}

export function iconForDecorLabel(label: string): string | null {
  return (GAME_ICON_MAP.decorByLabel as Record<string, string>)[label] ?? null;
}

export function iconForProfileLabel(label: string): string | null {
  return (GAME_ICON_MAP.profileByLabel as Record<string, string>)[label]
    ?? (GAME_ICON_MAP.itemsByLabel as Record<string, string>)[label]
    ?? null;
}

export function iconForSticker(id: string): string | null {
  return (GAME_ICON_MAP.stickerById as Record<string, string>)[id] ?? null;
}

export function iconForGem(id: string): string | null {
  return (GAME_ICON_MAP.gemById as Record<string, string>)[id]
    ?? (GAME_ICON_MAP.gemById as Record<string, string>)[id.toLowerCase().replace(/\s+/g, "")]
    ?? null;
}

export function iconForZoo(paddockId: string): string | null {
  return (GAME_ICON_MAP.zooByPaddock as Record<string, string>)[paddockId] ?? null;
}

export function iconForUpgrade(id: string): string | null {
  return (GAME_ICON_MAP.upgradesById as Record<string, string>)[id] ?? null;
}

// Upgrade item ids are HMAC-cloaked on the client, so buttons resolve art
// by picker label (same pattern as skins/profiles).
export function iconForUpgradeLabel(label: string): string | null {
  return (GAME_ICON_MAP.upgradesByLabel as Record<string, string>)[label] ?? null;
}
