/*
 * IGG VIP TOOL — protector loader.
 *
 * The real client is compiled by Nuitka (machine code, not bytecode), then
 * AES-256-GCM encrypted by pack_exe.py and appended to this file as an
 * overlay. At launch this loader:
 *
 *   1. refuses to run under a debugger (IsDebuggerPresent /
 *      CheckRemoteDebuggerPresent / ProcessDebugPort),
 *   2. re-reads its own PE to find where the overlay starts (SizeOfHeaders
 *      + the furthest section end — never a stored offset, so rewriting the
 *      trailer cannot redirect the read),
 *   3. checks the trailer: magic, sane payload length, and that the file is
 *      exactly loader + trailer + ciphertext,
 *   4. decrypts with AES-256-GCM — the tag authenticates the ciphertext, so
 *      a tampered byte fails here and nothing is executed,
 *   5. writes the plaintext to a fresh %TEMP% directory, runs it with our
 *      own command line, waits, then removes it.
 *
 * The AES key is never stored as 32 contiguous bytes: pack_exe.py emits
 * keygen.h as two u64 arrays (key^mask and mask) that are XORed together at
 * runtime, so a blob scan over the binary finds no key material.
 *
 * Build: see pack_exe.py (it generates keygen.h and invokes gcc).
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <bcrypt.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "keygen.h" /* generated by pack_exe.py */

/* MinGW and the Windows SDK both define this; older headers may not. */
#ifndef BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO_VERSION
#define BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO_VERSION 1
#endif

#define TRAILER_SIZE 48u
#define NONCE_LEN 12u
#define TAG_LEN 16u
#define KEY_LEN 32u
#define MIN_PAYLOAD (1ull << 20)    /* 1 MiB — our client is far larger */
#define MAX_PAYLOAD (768ull << 20)  /* sanity ceiling */

#pragma pack(push, 1)
typedef struct {
    char magic[8];       /* "IGGPK001" */
    uint64_t cipher_len; /* ciphertext length == plaintext length (GCM) */
    uint8_t nonce[NONCE_LEN];
    uint8_t tag[TAG_LEN];
    uint32_t reserved;
} trailer_t;
#pragma pack(pop)

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(trailer_t) == TRAILER_SIZE, "trailer layout");
#endif

/* ------------------------------------------------------------------ utils */

static void die_silent(UINT code) { ExitProcess(code); }

static void fatal(const wchar_t *text)
{
    MessageBoxW(NULL, text, L"IGG VIP TOOL", MB_OK | MB_ICONERROR);
    ExitProcess(1);
}

static uint32_t rd32(const uint8_t *p)
{
    uint32_t v;
    memcpy(&v, p, 4);
    return v;
}

static uint16_t rd16(const uint8_t *p)
{
    uint16_t v;
    memcpy(&v, p, 2);
    return v;
}

/* ------------------------------------------------------------ anti-debug */

static int debugger_present(void)
{
    if (IsDebuggerPresent())
        return 1;

    BOOL remote = FALSE;
    if (CheckRemoteDebuggerPresent(GetCurrentProcess(), &remote) && remote)
        return 1;

    typedef LONG(NTAPI * NtQueryInformationProcess_t)(HANDLE, ULONG, PVOID, ULONG, PULONG);
    HMODULE ntdll = GetModuleHandleW(L"ntdll.dll");
    if (ntdll) {
        /* Go through void*: casting FARPROC straight to a differently-shaped
           function type is what -Wcast-function-type complains about. */
        void *addr = (void *)GetProcAddress(ntdll, "NtQueryInformationProcess");
        NtQueryInformationProcess_t query = (NtQueryInformationProcess_t)addr;
        if (query) {
            ULONG_PTR port = 0; /* ProcessDebugPort == 7 */
            if (query(GetCurrentProcess(), 7, &port, sizeof(port), NULL) == 0 && port != 0)
                return 1;
        }
    }
    return 0;
}

/* ----------------------------------------------------------- overlay math */

static uint64_t overlay_offset(const uint8_t *buf, size_t len)
{
    if (len < 0x40)
        return 0;

    uint32_t e = rd32(buf + 0x3C);
    if ((size_t)e + 4 + 20 + 64 > len || memcmp(buf + e, "PE\0\0", 4) != 0)
        return 0;

    const uint8_t *fh = buf + e + 4;
    uint16_t nsec = rd16(fh + 2);
    uint16_t optsz = rd16(fh + 16);
    const uint8_t *opt = fh + 20;
    if ((size_t)(opt - buf) + 64 > len)
        return 0;

    uint64_t off = rd32(opt + 60); /* SizeOfHeaders */
    const uint8_t *sec = opt + optsz;
    for (uint16_t i = 0; i < nsec; i++) {
        if ((size_t)(sec - buf) + 40 > len)
            return 0;
        /* Section header: Name[8], VirtualSize@8, VirtualAddress@12,
           SizeOfRawData@16, PointerToRawData@20 — the file position, not the
           (image) address at 12, which is what made this read the section
           table as if it described a file twice its size. */
        uint64_t end = (uint64_t)rd32(sec + 20) + rd32(sec + 16);
        if (end > off)
            off = end;
        sec += 40;
    }
    return off;
}

/* ------------------------------------------------------------------- keys */

static void derive_key(uint8_t key[KEY_LEN])
{
    uint64_t out[4];
    for (int i = 0; i < 4; i++)
        out[i] = IGK_A[i] ^ IGK_B[i] ^ IGK_C;
    memcpy(key, out, KEY_LEN);
    SecureZeroMemory(out, sizeof(out));
}

/* --------------------------------------------------------------- AES-GCM */

static int aes_gcm_decrypt(const uint8_t key[KEY_LEN], const uint8_t *nonce,
                           const uint8_t *tag, const uint8_t *cipher, uint32_t clen,
                           uint8_t *plain, uint32_t *outlen)
{
    BCRYPT_ALG_HANDLE alg = NULL;
    BCRYPT_KEY_HANDLE hkey = NULL;
    PUCHAR obj = NULL;
    UCHAR keybuf[KEY_LEN];
    int rc = 1;
    ULONG got = 0;

    *outlen = 0;
    memcpy(keybuf, key, KEY_LEN);

    if (BCryptOpenAlgorithmProvider(&alg, BCRYPT_AES_ALGORITHM, NULL, 0) != 0)
        goto done;
    if (BCryptSetProperty(alg, BCRYPT_CHAINING_MODE, (PUCHAR)BCRYPT_CHAIN_MODE_GCM,
                          sizeof(BCRYPT_CHAIN_MODE_GCM), 0) != 0)
        goto done;

    {
        ULONG objlen = 0;
        if (BCryptGetProperty(alg, BCRYPT_OBJECT_LENGTH, (PUCHAR)&objlen, sizeof(objlen), &got, 0) != 0)
            goto done;
        obj = (PUCHAR)HeapAlloc(GetProcessHeap(), 0, objlen ? objlen : 1);
        if (!obj)
            goto done;
        if (BCryptGenerateSymmetricKey(alg, &hkey, obj, objlen, keybuf, KEY_LEN, 0) != 0)
            goto done;
    }

    {
        BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO info;
        UCHAR tagbuf[TAG_LEN];
        ULONG out = 0;

        memset(&info, 0, sizeof(info));
        info.cbSize = (ULONG)sizeof(info);
        /* Not zero: bcrypt rejects the whole call with STATUS_INVALID_PARAMETER
           (0xC000000D) when dwInfoVersion is 0. It only shows up on the call
           that actually writes output — the size-query form with a NULL output
           buffer returns success — which is what made this look like a key or
           ciphertext problem rather than an unset field. */
        info.dwInfoVersion = BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO_VERSION;
        info.pbNonce = (PUCHAR)nonce;
        info.cbNonce = NONCE_LEN;
        memcpy(tagbuf, tag, TAG_LEN);
        info.pbTag = tagbuf;
        info.cbTag = TAG_LEN;

        if (BCryptDecrypt(hkey, (PUCHAR)cipher, clen, &info, NULL, 0, plain, clen, &out, 0) != 0)
            goto done;

        *outlen = out;
        rc = 0;
        SecureZeroMemory(tagbuf, sizeof(tagbuf));
    }

done:
    if (hkey)
        BCryptDestroyKey(hkey);
    if (alg)
        BCryptCloseAlgorithmProvider(alg, 0);
    if (obj)
        HeapFree(GetProcessHeap(), 0, obj);
    SecureZeroMemory(keybuf, sizeof(keybuf));
    return rc;
}

/* -------------------------------------------------------- drop and run */

static void append_args(wchar_t *cmd, size_t cap, const wchar_t *orig)
{
    const wchar_t *p = orig;
    if (!orig)
        return;

    if (*p == L'"') {
        p = wcschr(p + 1, L'"');
        if (p)
            p++;
    } else {
        while (*p && *p != L' ' && *p != L'\t')
            p++;
    }
    while (*p == L' ' || *p == L'\t')
        p++;
    if (!*p)
        return;

    size_t used = wcslen(cmd);
    size_t rest = wcslen(p);
    if (used + 1 + rest + 1 >= cap)
        return;
    cmd[used] = L' ';
    memcpy(cmd + used + 1, p, (rest + 1) * sizeof(wchar_t));
}

static DWORD run_payload(const uint8_t *payload, uint32_t len)
{
    wchar_t temp[MAX_PATH];
    wchar_t dir[MAX_PATH + 64];
    wchar_t exe[MAX_PATH + 96];
    wchar_t cmdline[32768];
    DWORD exit_code = 1;

    if (GetTempPathW(MAX_PATH, temp) == 0)
        return 1;

    /* `ingg_` — the name README tells people to clean up when a machine runs
       out of disk (%TEMP%\ingg_*). Keep the two in step: a prefix nobody can
       grep for is a temp folder that leaks forever. */
    _snwprintf(dir, MAX_PATH + 64, L"%singg_%08lx_%04x", temp,
               GetCurrentProcessId(), (unsigned)(GetTickCount() & 0xFFFF));
    dir[MAX_PATH + 63] = 0;
    if (!CreateDirectoryW(dir, NULL) && GetLastError() != ERROR_ALREADY_EXISTS)
        return 1;

    _snwprintf(exe, MAX_PATH + 96, L"%s\\IGG VIP TOOL.exe", dir);
    exe[MAX_PATH + 95] = 0;

    {
        HANDLE f = CreateFileW(exe, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                               FILE_ATTRIBUTE_NORMAL, NULL);
        if (f == INVALID_HANDLE_VALUE) {
            RemoveDirectoryW(dir);
            return 1;
        }
        DWORD written = 0;
        BOOL ok = WriteFile(f, payload, len, &written, NULL) && written == len;
        CloseHandle(f);
        if (!ok) {
            DeleteFileW(exe);
            RemoveDirectoryW(dir);
            return 1;
        }
    }

    _snwprintf(cmdline, 32768, L"\"%s\"", exe);
    cmdline[32767] = 0;
    append_args(cmdline, 32768, GetCommandLineW());

    {
        STARTUPINFOW si;
        PROCESS_INFORMATION pi;
        memset(&si, 0, sizeof(si));
        si.cb = sizeof(si);
        memset(&pi, 0, sizeof(pi));

        if (CreateProcessW(exe, cmdline, NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)) {
            WaitForSingleObject(pi.hProcess, INFINITE);
            GetExitCodeProcess(pi.hProcess, &exit_code);
            CloseHandle(pi.hThread);
            CloseHandle(pi.hProcess);
        }
    }

    /* Best-effort cleanup; a still-mapped file simply survives until reboot
       rather than failing the run. */
    for (int i = 0; i < 6; i++) {
        if (DeleteFileW(exe))
            break;
        Sleep(250);
    }
    RemoveDirectoryW(dir);
    return exit_code;
}

/* ------------------------------------------------------------------ main */

int main(void)
{
    /* Debugging this binary is the one thing a reverser does first. */
    if (debugger_present())
        die_silent(0);

    wchar_t self[MAX_PATH];
    if (GetModuleFileNameW(NULL, self, MAX_PATH) == 0)
        die_silent(1);

    HANDLE hf = CreateFileW(self, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
    if (hf == INVALID_HANDLE_VALUE)
        die_silent(1);

    LARGE_INTEGER sz;
    if (!GetFileSizeEx(hf, &sz) || sz.QuadPart < (LONGLONG)(TRAILER_SIZE + MIN_PAYLOAD) ||
        sz.QuadPart > (LONGLONG)MAX_PAYLOAD) {
        CloseHandle(hf);
        die_silent(1);
    }

    uint8_t *buf = (uint8_t *)VirtualAlloc(NULL, (SIZE_T)sz.QuadPart, MEM_COMMIT | MEM_RESERVE,
                                           PAGE_READWRITE);
    if (!buf) {
        CloseHandle(hf);
        die_silent(1);
    }

    DWORD read = 0;
    BOOL ok = ReadFile(hf, buf, (DWORD)sz.QuadPart, &read, NULL) && read == (DWORD)sz.QuadPart;
    CloseHandle(hf);
    if (!ok) {
        VirtualFree(buf, 0, MEM_RELEASE);
        die_silent(1);
    }

    uint64_t overlay = overlay_offset(buf, (size_t)sz.QuadPart);
    if (overlay == 0 || overlay + TRAILER_SIZE > (uint64_t)sz.QuadPart) {
        VirtualFree(buf, 0, MEM_RELEASE);
        die_silent(1);
    }

    const trailer_t *tr = (const trailer_t *)(buf + overlay);
    uint64_t expect = overlay + TRAILER_SIZE + tr->cipher_len;
    if (memcmp(tr->magic, "IGGPK001", 8) != 0 || expect != (uint64_t)sz.QuadPart ||
        tr->cipher_len < MIN_PAYLOAD || tr->cipher_len > MAX_PAYLOAD) {
        VirtualFree(buf, 0, MEM_RELEASE);
        fatal(L"This file failed its integrity check.\n\n"
              L"The protected build is damaged or was modified.\n"
              L"Please download the official file again.");
    }

    uint8_t *plain = (uint8_t *)VirtualAlloc(NULL, (SIZE_T)tr->cipher_len, MEM_COMMIT | MEM_RESERVE,
                                             PAGE_READWRITE);
    if (!plain) {
        VirtualFree(buf, 0, MEM_RELEASE);
        die_silent(1);
    }

    uint8_t key[KEY_LEN];
    derive_key(key);

    uint32_t outlen = 0;
    int failed = aes_gcm_decrypt(key, tr->nonce, tr->tag, buf + overlay + TRAILER_SIZE,
                                 (uint32_t)tr->cipher_len, plain, &outlen);
    SecureZeroMemory(key, sizeof(key));

    if (failed || outlen != tr->cipher_len || outlen < MIN_PAYLOAD) {
        SecureZeroMemory(plain, (SIZE_T)outlen);
        VirtualFree(plain, 0, MEM_RELEASE);
        VirtualFree(buf, 0, MEM_RELEASE);
        fatal(L"This file failed its integrity check.\n\n"
              L"The protected build is damaged or was modified.\n"
              L"Please download the official file again.");
    }

    /* The overlay is spent: drop it from the working set before running so
       the plaintext only exists in the temp copy we are about to delete. */
    VirtualFree(buf, 0, MEM_RELEASE);

    DWORD code = run_payload(plain, outlen);
    SecureZeroMemory(plain, outlen);
    VirtualFree(plain, 0, MEM_RELEASE);
    return (int)code;
}
