#!/usr/bin/env python3
"""Protect a built EXE: AES-256-GCM encrypt it and wrap it in the C loader.

    python pack_exe.py --payload build/IGG\\ VIP\\ TOOL.exe --output "dist/IGG VIP TOOL.exe"

The output is  loader.exe  ++  48-byte trailer  ++  ciphertext:

    trailer: magic[8] = "IGGPK001" | cipher_len u64 LE | nonce[12] |
             gcm_tag[16] | reserved u32

The trailer is at the overlay start because that is where loader.c reads it;
the authenticated ciphertext follows it.

The AES key exists only inside the compiled loader, and even there never as
32 contiguous bytes: it is emitted as two u64 arrays (key^mask, mask) that
are XORed together at runtime (see loader.c / derive_key).

No secrets are needed at build time beyond `cryptography`, and the compiler
search order is: $CC, PATH gcc, Nuitka's own MinGW cache, then the usual
MSYS2/MinGW install locations.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import secrets
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent

TRAILER_MAGIC = b"IGGPK001"
TRAILER_SIZE = 48
KEY_LEN = 32
NONCE_LEN = 12
TAG_LEN = 16

# Sanity bounds, mirrored in loader.c (MIN_PAYLOAD / MAX_PAYLOAD).
MIN_PAYLOAD = 1 << 20   # 1 MiB
MAX_PAYLOAD = 768 << 20  # 768 MiB


# --------------------------------------------------------------------- key

def write_key_header(key: bytes, path: Path) -> None:
    """Emit keygen.h: the key split into masked u64 halves, never contiguous."""
    assert len(key) == KEY_LEN
    mask = [secrets.randbits(64) for _ in range(4)]
    const = secrets.randbits(64)
    a = [int.from_bytes(key[i * 8:(i + 1) * 8], "little") ^ mask[i] ^ const for i in range(4)]
    lines = [
        "/* generated by pack_exe.py — do not edit, do not commit */",
        "#ifndef IGG_KEYGEN_H",
        "#define IGG_KEYGEN_H",
        "static const unsigned long long IGK_A[4] = {"
        + ", ".join(f"0x{v:016x}ULL" for v in a)
        + "};",
        "static const unsigned long long IGK_B[4] = {"
        + ", ".join(f"0x{v:016x}ULL" for v in mask)
        + "};",
        f"static const unsigned long long IGK_C = 0x{const:016x}ULL;",
        "#endif",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def roundtrip_key_header(key: bytes, path: Path) -> bytes:
    """Read keygen.h back the way loader.c does — used by the unit test."""
    import re

    text = path.read_text(encoding="utf-8")

    def arr(name: str) -> list[int]:
        m = re.search(rf"{name}\[4\] = \{{([^}}]*)\}}", text)
        if not m:
            raise ValueError(f"{name} not found")
        return [int(v.strip().removesuffix("ULL"), 16) for v in m.group(1).split(",") if v.strip()]

    m = re.search(r"IGK_C = (0x[0-9a-f]+)ULL", text)
    if not m:
        raise ValueError("IGK_C not found")
    const = int(m.group(1), 16)
    a, b = arr("IGK_A"), arr("IGK_B")
    out = b"".join(((a[i] ^ b[i] ^ const) & ((1 << 64) - 1)).to_bytes(8, "little") for i in range(4))
    return out


# ---------------------------------------------------------------- trailer

def pack_trailer(cipher_len: int, nonce: bytes, tag: bytes) -> bytes:
    assert len(nonce) == NONCE_LEN and len(tag) == TAG_LEN
    return struct.pack("<8sQ", TRAILER_MAGIC, cipher_len) + nonce + tag + struct.pack("<I", 0)


def unpack_trailer(blob: bytes) -> dict:
    magic, cipher_len = struct.unpack_from("<8sQ", blob, 0)
    nonce = blob[16:16 + NONCE_LEN]
    tag = blob[16 + NONCE_LEN:16 + NONCE_LEN + TAG_LEN]
    reserved = struct.unpack_from("<I", blob, 16 + NONCE_LEN + TAG_LEN)[0]
    return {
        "magic": magic,
        "cipher_len": cipher_len,
        "nonce": nonce,
        "tag": tag,
        "reserved": reserved,
    }


def overlay_offset(buf: bytes) -> int:
    """Where the overlay starts, computed from the PE headers exactly the way
    loader.c does: SizeOfHeaders and the furthest section end."""
    if len(buf) < 0x40:
        raise ValueError("not a PE")
    e = struct.unpack_from("<I", buf, 0x3C)[0]
    if buf[e:e + 4] != b"PE\0\0":
        raise ValueError("missing PE signature")
    fh = e + 4
    nsec = struct.unpack_from("<H", buf, fh + 2)[0]
    optsz = struct.unpack_from("<H", buf, fh + 16)[0]
    opt = fh + 20
    off = struct.unpack_from("<I", buf, opt + 60)[0]
    sec = opt + optsz
    for i in range(nsec):
        # Section header: Name[8], VirtualSize@8, VirtualAddress@12,
        # SizeOfRawData@16, PointerToRawData@20. Offset 12 is the *image*
        # address and must not be used as a file position.
        start = struct.unpack_from("<I", buf, sec + i * 40 + 20)[0]
        size = struct.unpack_from("<I", buf, sec + i * 40 + 16)[0]
        off = max(off, start + size)
    return off


# --------------------------------------------------------------- compiler

def find_gcc(explicit: str | None = None) -> str:
    """Locate a MinGW gcc: $CC, PATH, Nuitka's cached MinGW, common installs."""
    if explicit:
        return explicit
    if os.environ.get("CC"):
        return os.environ["CC"]
    on_path = shutil.which("gcc")
    if on_path:
        return on_path

    roots = [
        Path(os.environ.get("LOCALAPPDATA", "")) / "Nuitka",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Programs",
        Path(r"C:\msys64"),
        Path(r"C:\mingw64"),
        Path(r"C:\MinGW"),
        Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "mingw64",
    ]
    for root in roots:
        if not root.is_dir():
            continue
        for hit in sorted(root.rglob("gcc.exe")):
            # Skip compiler-adapter copies inside ccache wrappers.
            if hit.parent.name in ("bin", "mingw64", "mingw32"):
                return str(hit)

    raise SystemExit(
        "gcc not found. Nuitka downloads a MinGW-w64 toolchain on first build\n"
        "(`--assume-yes-for-downloads --mingw64`); run that once, or pass --gcc."
    )


def compile_loader(gcc: str, out: Path, include_dir: Path, work: Path) -> None:
    cmd = [
        gcc,
        "-O2",
        "-std=c11",
        "-Wall",
        "-Wextra",
        "-mwindows",           # windowed subsystem: no console window (PE subsystem 2)
        "-static",             # self-contained: no libgcc/libwinpthread beside it
        "-s",                  # strip symbols
        "-I", str(include_dir),
        "-o", str(out),
        str(HERE / "loader.c"),
        "-lbcrypt",            # AES-256-GCM (Windows CNG)
        "-luser32",            # MessageBoxW
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(
            "loader build failed:\n"
            + " ".join(cmd)
            + "\n\n"
            + proc.stdout
            + proc.stderr
        )


# ------------------------------------------------------------------- main

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--payload", required=True, type=Path, help="EXE to protect (Nuitka output)")
    ap.add_argument("--output", required=True, type=Path, help="final protected EXE")
    ap.add_argument("--gcc", help="gcc to use (default: auto-detect)")
    ap.add_argument("--keep", action="store_true", help="keep the intermediate loader EXE")
    args = ap.parse_args(argv)

    payload = args.payload.read_bytes()
    if len(payload) < MIN_PAYLOAD:
        raise SystemExit(f"payload is only {len(payload)} bytes — refusing to protect it")
    if len(payload) > MAX_PAYLOAD:
        raise SystemExit(f"payload is {len(payload)} bytes — above the loader's ceiling")
    if payload[:2] != b"MZ":
        raise SystemExit("payload is not a Windows EXE")

    key = secrets.token_bytes(KEY_LEN)
    nonce = secrets.token_bytes(NONCE_LEN)

    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError as exc:  # pragma: no cover - environment problem
        raise SystemExit("pip install cryptography (needed to encrypt the payload)") from exc

    sealed = AESGCM(key).encrypt(nonce, payload, None)  # ciphertext || 16-byte tag
    cipher, tag = sealed[:-TAG_LEN], sealed[-TAG_LEN:]

    with tempfile.TemporaryDirectory(prefix="iggpack-") as tmp:
        work = Path(tmp)
        write_key_header(key, work / "keygen.h")
        loader = work / "loader.exe"
        compile_loader(find_gcc(args.gcc), loader, work, work)
        loader_bytes = loader.read_bytes()
        if loader_bytes[:2] != b"MZ":
            raise SystemExit("compiled loader is not a Windows EXE")

        start = overlay_offset(loader_bytes)
        if start > len(loader_bytes):
            raise SystemExit("could not locate the loader's overlay start")
        # Trim anything past the last section (linker alignment padding): the
        # loader recomputes `start` from the PE headers, so the ciphertext has
        # to begin exactly there or its size check will reject our own file.
        loader_bytes = loader_bytes[:start]

        trailer = pack_trailer(len(cipher), nonce, tag)
        # Layout: loader || trailer || ciphertext. The trailer sits *at* the
        # overlay start because loader.c reads it there before it knows the
        # payload length; the ciphertext follows it. The loader's own size
        # check (overlay + TRAILER_SIZE + cipher_len == file size) pins the
        # order — a reordered file fails there rather than being executed.
        blob = loader_bytes + trailer + cipher

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(blob)

        if args.keep:
            keep = args.output.with_suffix(".loader.exe")
            keep.write_bytes(loader_bytes)
            print(f"kept intermediate loader: {keep}")

    # Verify what we just produced, before anyone ships it.
    out = args.output.read_bytes()
    start = overlay_offset(out)
    tr = unpack_trailer(out[start:start + TRAILER_SIZE])
    if tr["magic"] != TRAILER_MAGIC:
        raise SystemExit("verification failed: trailer magic missing")
    if start + TRAILER_SIZE + tr["cipher_len"] != len(out):
        raise SystemExit("verification failed: size does not match trailer")

    sha = hashlib.sha256(out).hexdigest()
    print(f"protected : {args.output}")
    print(f"  payload : {len(payload):,} bytes (AES-256-GCM)")
    print(f"  loader  : {start:,} bytes")
    print(f"  total   : {len(out):,} bytes")
    print(f"  sha256  : {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
